// Language dictionaries and translation helpers.

let currentLang = localStorage.getItem(typeof LANG_KEY !== "undefined" ? LANG_KEY : "documents-workbench-lang") === "en" ? "en" : "pl";
let BASE_TITLE = document.title || "Documents Workbench";

const I18N = {
  pl: {
    locale: "pl-PL",
    title: "Documents Workbench",
    description: "Lokalne przeglądanie, edycja i analiza dokumentów Word",
    online: "Online",
    offline: "Offline",
    panelOpen: "Zamknij panel",
    panelClosed: "Panel",
    noFile: "Brak pliku",
    loadingGeneric: "Ładowanie…",
    loadingFile: "Wczytywanie dokumentu…",
    renderingDoc: "Renderowanie dokumentu…",
    savingFile: "Zapisywanie…",
    docLoaded: "Dokument wczytany",
    sampleLoaded: "Przykładowy dokument wczytany",
    unsupportedType: "Obsługiwane formaty: .docx, .pdf i zdjęcia dokumentów (.jpg, .png, .heic) — PDF i zdjęcie zamieniają się w .docx",
    photoPreparing: "Przygotowywanie zdjęcia ({n})…",
    photoDecodeFailed: "Nie udało się odczytać zdjęcia — zapisz je jako JPG lub PNG i spróbuj ponownie.",
    photoHeicUnsupported: "Ta przeglądarka nie odczytuje zdjęć HEIC (iPhone). Zapisz zdjęcie jako JPG (albo otwórz w Safari) i spróbuj ponownie.",
    photoPagesShort: "str.",
    pdfSoon: "PDF nie jest jeszcze obsługiwany — otwórz plik .docx.",
    docOldFormat: "To stary format .doc — w Wordzie wybierz „Zapisz jako” → Dokument programu Word (.docx) i otwórz ten plik.",
    libsMissingStatus: "Brak bibliotek dokumentu",
    libsMissingToast: "Nie udało się wczytać bibliotek DOCX",
    noFileToSave: "Najpierw wczytaj dokument",
    saveDone: "Zapisano dokument",
    saveFailed: "Nie udało się zapisać pliku",
    saveAsPrompt: "Nazwa pliku",
    saveInPlaceWarn: "Zapisać zmiany w oryginalnym pliku „{name}”? (Następne „Zapisz” już bez pytania.)",
    saveDifferentFileWarn: "Wybrany plik to „{name}”, nie bieżący dokument. Nadpisać mimo to?",
    saveCancelled: "Anulowano zapis",
    draftTitle: "Niezapisana praca",
    draftChangedAt: "zmieniony {when}",
    draftChanges: "zmiany: {count}",
    draftToday: "dziś o {time}",
    draftYesterday: "wczoraj o {time}",
    draftRestore: "Przywróć",
    draftDiscard: "Odrzuć",
    draftDiscardConfirm: "Usunąć niezapisane zmiany w „{name}”? Tego nie da się cofnąć.",
    draftRestored: "Przywrócono niezapisaną pracę: {name}. Zapisz, żeby jej nie stracić.",
    draftGone: "Tego szkicu już nie ma.",
    draftRestoreFailed: "Nie udało się przywrócić szkicu.",
    draftOriginalChanged: "Plik „{name}” na dysku zmienił się od czasu szkicu — „Zapisz” utworzy kopię, żeby niczego nie nadpisać.",
    draftNote: "Szkic jest tylko na tym urządzeniu i znika sam po 7 dniach.",
    draftMore: "Pozostałe niezapisane prace ({count})",
    linkBack: "↩ Wróć (Alt+←)",
    linkTargetMissing: "Tego miejsca nie ma w dokumencie (zakładka usunięta albo w innym pliku).",
    linkUnsupported: "Tego linku nie da się otworzyć tutaj (plik na dysku albo nieobsługiwany adres) — otwórz go w Wordzie.",
    openExternalFailed: "Nie udało się otworzyć przekazanego pliku — otwórz go przyciskiem „Otwórz”.",
    saveDownloaded: "Plik „{name}” pobrany — znajdziesz go w Pobranych (na iPhonie: Pliki → Pobrane).",
    savePickFileHint: "Wskaż plik .docx, który chcesz nadpisać",
    savePermissionDenied: "Brak uprawnień do zapisu w tym miejscu",
    editApplied: "Zastosowano zmiany: {count}",
    editNothing: "Brak zmian do zastosowania",
    editErrNoFind: "Podaj szukany tekst",
    editErrBadRegex: "Niepoprawne wyrażenie regularne",
    editErrNoAffix: "Podaj prefiks lub sufiks",
    editToolNoChange: "Brak zmian do zastosowania",
    editOpLabel: "Operacja",
    editOpReplace: "Znajdź i zamień",
    editOpCase: "Zmiana wielkości",
    editOpTrim: "Przytnij / spacje",
    editOpAffix: "Prefiks / sufiks",
    editCaseLabel: "Wielkość liter",
    editCaseUpper: "WIELKIE",
    editCaseLower: "małe",
    editCaseTitle: "Jak Nazwa Własna",
    editTrimLabel: "Tryb",
    editTrimEnds: "Przytnij końce",
    editTrimCollapse: "Zwiń wielokrotne spacje",
    editTrimHard: "Zamień twarde spacje",
    editPrefixLabel: "Prefiks (z przodu)",
    editSuffixLabel: "Sufiks (z tyłu)",
    inlineEditHint: "Enter — akapit · Shift+Enter — linia · Backspace — scal · Tab — lista · Ctrl+Tab — nagłówek · Ctrl+B/I/U — styl · rozmiar z listy (dziedziczy z akapitu)",
    searchNoMatches: "Brak trafień",
    searchMatches: "{count} trafień",
    readModeOn: "Tylko odczyt",
    readModeOff: "Tryb edycji",
    words: "Słowa",
    chars: "Znaki",
    headings: "Nagłówki",
    paragraphs: "Akapity",
    tables: "Tabele",
    editToolsPanel: "Narzędzia edycji",
    editFindLabel: "Szukaj",
    editReplaceLabel: "Zamień na",
    editRegexLabel: "Wyrażenie regularne",
    editScopeLabel: "Zakres",
    editScopeAll: "Cały dokument",
    editScopeBody: "Treść główna",
    applyEdit: "Zastosuj",
    searchPanel: "Wyszukiwanie",
    frMatchCase: "Rozróżniaj wielkość liter",
    frWholeWord: "Tylko całe słowa",
    frRegexHint: "W polu „Zamień na”: $1, $2… = grupy z nawiasów, $& = całe trafienie.",
    frScopeLabel: "Szukaj w",
    frScopeAll: "Cała treść",
    frScopeHeadings: "Tylko nagłówki sekcji",
    frOtherPartsLabel: "„Zamień wszystkie” także w nagłówkach, stopkach i przypisach",
    frOtherFoundOn: "+{count} w nagłówkach, stopkach, przypisach (też zostaną zamienione)",
    frOtherFoundOff: "+{count} w nagłówkach, stopkach, przypisach (zaznacz opcję, żeby je też zamienić)",
    frReplaceAllOther: "Oraz {count} w nagłówkach, stopkach i przypisach.",
    frListMore: "…i jeszcze {count} (przejdź ↑ ↓)",
    grammarRescanned: "Tekst zmienił się od skanu — sugestie odświeżone, kliknij jeszcze raz.",
    snippetsFieldsTitle: "Uzupełnij pola: {name}",
    snippetsFieldsHint: "Puste pole zostanie w tekście jako {{pole}} — możesz je wypełnić później w panelu Placeholdery. Wartości są zapamiętywane na następny raz.",
    snippetsFieldsInsert: "Wstaw",
    snippetsAddField: "＋ Pole (kalendarz, lista…)",
    snippetsFieldTitle: "Pole w snippecie",
    snippetsFieldName: "Nazwa pola",
    snippetsFieldType: "Rodzaj",
    snippetsFieldTypeText: "Tekst",
    snippetsFieldTypeLong: "Tekst wielowierszowy",
    snippetsFieldTypeNumber: "Liczba",
    snippetsFieldTypeDate: "Data (kalendarz)",
    snippetsFieldTypeList: "Lista wyboru",
    snippetsFieldTypeCheck: "Pole wyboru ☐ / ☒",
    snippetsFieldTypeYesNo: "Tak / Nie",
    snippetsFieldOptions: "Pozycje listy (każda w osobnym wierszu)",
    snippetsFieldDateFormat: "Format daty",
    snippetsFieldDateShort: "04.10.2026",
    snippetsFieldDateLong: "4 października 2026",
    snippetsFieldDateIso: "2026-10-04",
    snippetsFieldForm: "Wstaw jako pole formularza Worda (wypełniane później w dokumencie, też w Wordzie)",
    snippetsFieldFormHint: "Bez tego: przy wstawianiu snippetu pojawi się okienko (kalendarz, lista…), a do dokumentu trafi wybrana wartość.",
    snippetsFieldAdd: "Dodaj do treści",
    snippetsFieldNameMissing: "Podaj nazwę pola.",
    snippetsFieldListMissing: "Wpisz co najmniej jedną pozycję listy.",
    snippetsSuggestHint: "↑ ↓ wybór · Enter/Tab wstaw · Esc zamknij",
    snippetsStarter: "Dodaj przykładowe snippety",
    snippetsStarterAdded: "Dodano przykładowe snippety: {count}",
    snippetsFilter: "Szukaj snippetu…",
    snippetsInsertShort: "Wstaw",
    snippetsEdit: "Edytuj",
    snippetsUpdated: "Zaktualizowano {name}",
    cancel: "Anuluj",
    undoOpSnippet: "snippet",
    frPanel: "Znajdź i zamień",
    frPrev: "Poprzednie",
    frNext: "Następne",
    frScan: "Szukaj",
    frReplaceOne: "Zamień bieżące",
    frReplaceAll: "Zamień wszystkie",
    frMatchPos: "Trafienie {pos} / {total}",
    frPreviewOnly: "Podgląd zapisu: {hits} wystąpień w {paras} akapitach",
    frReplaceAllConfirm: "Zamienić {hits} wystąpień w {paras} akapitach?",
    frReplacedOne: "Zamieniono bieżące trafienie",
    searchQueryLabel: "Fraza",
    searchScopeLabel: "Zakres",
    searchHighlight: "Podświetl",
    structurePanel: "Struktura",
    structureFilterLabel: "Pokaż",
    structureFilterAll: "Wszystko",
    structureFilterHeadings: "Nagłówki",
    structureFilterParagraphs: "Akapity",
    structureFilterTables: "Tabele",
    structureTypeHeading: "Nagł.",
    structureTypeParagraph: "Akap.",
    structureTypeTable: "Tabela",
    structureCopy: "Kopiuj",
    structureEdit: "Edytuj",
    structureQuickEditLabel: "Szybka edycja akapitu",
    structureQuickApply: "Zastosuj",
    structureQuickFocus: "Edytuj w podglądzie",
    structureCopied: "Skopiowano tekst",
    structureCopyFailed: "Nie udało się skopiować",
    structureNoOutline: "Brak elementów w dokumencie",
    structureNoFilterMatch: "Brak elementów w tym filtrze",
    structureEmptyPara: "(pusty akapit)",
    structureTablePreview: "Tabela {rows}×{cols}: {preview}",
    structureTableEmpty: "Tabela {rows}×{cols}",
    structureOutlineTruncated: "Pokazano {shown} z {total} elementów",
    structureSearchLabel: "Szukaj w strukturze",
    structureSearchPlaceholder: "fraza w nagłówku lub akapicie…",
    structurePageSizeLabel: "Na stronie",
    structurePageInfo: "{start}–{end} z {total} · str. {page}/{pages}",
    structurePrevPage: "Poprzednia",
    structureNextPage: "Następna",
    structureSearchNoMatch: "Brak trafień wyszukiwania",
    lockTracked: "Akapit ma śledzone zmiany — zaakceptuj lub odrzuć je w panelu Recenzja, żeby go edytować.",
    lockNote: "Odnośnik do przypisu stoi tu w nietypowym miejscu (np. w linku) — edycja tutaj by go zgubiła. Edytuj ten akapit w Wordzie.",
    lockPageBreakOnly: "Podział strony. Usuniesz go jak w Wordzie: Backspace na początku następnego akapitu albo Delete na końcu poprzedniego.",
    pageBreakOnlyLabel: "Podział strony",
    lockPageBreak: "Akapit ma w środku podział strony — edycja tutaj zamieniłaby go na zwykłe złamanie wiersza. Edytuj go w Wordzie.",
    lockNoteText: "Ten przypis ma element, którego edycja tutaj by nie zachowała (np. tabelę, pole, śledzoną zmianę) — edytuj go w Wordzie.",
    noteHintJumpRead: "Kliknij — przejdź do przypisu",
    noteHintJumpEdit: "Dwuklik — przejdź do przypisu i edytuj",
    lockObject: "Akapit zawiera obraz lub obiekt — edycja tutaj by go zgubiła. Edytuj go w Wordzie.",
    lockSymbol: "Akapit zawiera symbol Worda (np. z kroju Symbol) razem z tekstem — edycja tutaj by go zgubiła. Edytuj go w Wordzie.",
    lockField: "Akapit zawiera pole (np. numer strony, spis treści) — edycja tutaj by je zgubiła.",
    lockLink: "Akapit zawiera link — edycja tutaj by go zgubiła. Edytuj go w Wordzie.",
    reviewPanel: "Recenzja",
    reviewAuthorLabel: "Autor zmian",
    reviewAcceptAllBtn: "Akceptuj wszystkie",
    reviewRejectAllBtn: "Odrzuć wszystkie",
    reviewAcceptAll: "Akceptuj wszystkie",
    reviewRejectAll: "Odrzuć wszystkie",
    reviewAcceptAuthor: "Akceptuj: {author}",
    reviewRejectAuthor: "Odrzuć: {author}",
    reviewAllAuthors: "Wszyscy autorzy ({count})",
    reviewChangesHead: "Śledzone zmiany",
    reviewCommentsHead: "Komentarze",
    reviewNotesHead: "Przypisy",
    reviewRemoveComments: "Usuń wszystkie komentarze",
    reviewPreviewHint: "Podgląd pokazuje tekst tak, jakby zmiany były już zaakceptowane (usunięć w nim nie widać). Lista obok pokazuje wszystko.",
    reviewSummary: "Zmiany: {changes} (autorzy: {authors}) · komentarze: {comments} · przypisy: {notes}",
    reviewNoChanges: "Brak śledzonych zmian.",
    reviewNoComments: "Brak komentarzy.",
    reviewNoNotes: "Brak przypisów.",
    reviewShowMore: "Pokaż pozostałe ({count})",
    reviewKindIns: "Wstawiono",
    reviewKindDel: "Usunięto",
    reviewKindMoveFrom: "Przeniesiono stąd",
    reviewKindMoveTo: "Przeniesiono tu",
    reviewKindFormat: "Formatowanie",
    reviewKindParaFormat: "Format akapitu",
    reviewKindOtherFormat: "Inna zmiana układu",
    reviewKindParaIns: "Nowy akapit",
    reviewKindParaDel: "Połączenie akapitów",
    reviewKindRowIns: "Wstawiony wiersz",
    reviewKindRowDel: "Usunięty wiersz",
    reviewInHeader: "w nagłówku",
    reviewInFooter: "w stopce",
    reviewInFootnote: "w przypisie",
    reviewInEndnote: "w przypisie końcowym",
    reviewFootnote: "Przypis",
    reviewEndnote: "Przypis końcowy",
    reviewResolved: "rozwiązany",
    reviewAcceptOne: "Akceptuj zmianę",
    reviewRejectOne: "Odrzuć zmianę",
    reviewDeleteComment: "Usuń komentarz",
    reviewAcceptConfirm: "Zaakceptować zmiany ({count})?",
    reviewRejectConfirm: "Odrzucić zmiany ({count})?",
    reviewRemoveCommentsConfirm: "Usunąć wszystkie komentarze ({count}) z pliku?",
    reviewAccepted: "Zaakceptowano: {count}",
    reviewRejected: "Odrzucono: {count}",
    reviewCommentsRemoved: "Usunięto komentarze: {count}",
    reviewOnOpen: "Dokument ma śledzone zmiany ({changes}) i komentarze ({comments}) — zobacz panel Recenzja.",
    undoOpReview: "recenzja",
    undoOpForm: "pole formularza",
    lockForm: "Akapit zawiera pole formularza Worda — kliknij pole, żeby je wypełnić (albo panel Formularz). Reszty akapitu tu nie edytujesz, bo pole by się rozpadło.",
    formsPanel: "Formularz",
    formsOnOpen: "Ten dokument to formularz Worda ({count} pól) — kliknij pole w dokumencie albo otwórz panel Formularz.",
    formsSummary: "Pola: {count} · do uzupełnienia: {empty}",
    formsNone: "Ten dokument nie ma pól formularza Worda (list, dat, pól wyboru).",
    formsProtected: "Autor chronił ten dokument w Wordzie: można w nim tylko wypełniać pola.",
    formsShade: "Wyróżniaj pola w dokumencie",
    formsHint: "Listy, daty, pola wyboru i pola tekstowe z Worda. Kliknij pole w dokumencie albo zmień je tutaj — w Wordzie formularz dalej działa.",
    formsKindCheckbox: "pole wyboru",
    formsKindDropdown: "lista",
    formsKindCombo: "lista lub tekst",
    formsKindDate: "data",
    formsKindText: "tekst",
    formsLegacy: "starsze pole",
    formsCopies: "w {count} miejscach",
    formsLockedShort: "zablokowane",
    formsLocked: "To pole jest zablokowane w Wordzie — jego treści nie można zmienić.",
    formsJump: "Pokaż pole w dokumencie",
    formsToday: "Dziś",
    formsUnnamed: "Pole bez nazwy",
    undoOpInsert: "wstawienie",
    undoOpPaste: "wklejenie",
    exportPanel: "Eksport",
    exportIntro: "Pobierz treść dokumentu (razem z Twoimi edycjami) jako tekst, Markdown lub HTML. Wszystko lokalnie.",
    exportPrint: "Drukuj / zapisz jako PDF",
    exportPrintHint: "W oknie druku wybierz „Zapisz jako PDF”. Układ stron jak w podglądzie.",
    exportEmpty: "Dokument nie ma tekstu do wyeksportowania.",
    exportDone: "Zapisano {name}",
    exportPrintFail: "Nie udało się otworzyć okna druku.",
    statsPanel: "Statystyki",
    statsWords: "Słowa",
    statsChars: "Znaki",
    statsCharsNoSpaces: "Znaki bez spacji",
    statsSentences: "Zdania",
    statsParagraphs: "Akapity",
    statsTables: "Tabele",
    statsReading: "Czas czytania",
    statsAvgSentence: "Słów na zdanie",
    statsUnderMinute: "< 1 min",
    statsMinutes: "{n} min",
    statsTopWords: "Najczęstsze słowa",
    statsNoRepeats: "Brak powtarzających się słów (4+ liter).",
    statsLongLimit: "Długie zdanie = więcej niż (słów)",
    statsLongHead: "Najdłuższe zdania",
    statsNoLong: "Brak zdań dłuższych niż ustalony próg.",
    statsWordsShort: "{n} słów",
    statsRefresh: "Odśwież",
    statsSelectionHint: "Zaznacz fragment w dokumencie, a zobaczysz jego statystyki.",
    statsSelection: "Zaznaczenie: {words} słów · {chars} znaków · czytanie {min}",
    metadataScrub: "Usuń dane osobowe",
    metadataScrubConfirm: "Wyczyścić autora, ostatnio zmieniającego, opis i temat w pliku?",
    metadataScrubbed: "Dane osobowe usunięte z metadanych.",
    metadataScrubNothing: "Metadane były już czyste.",
    phExportValues: "Zapisz wartości (JSON)",
    phImportValues: "Wczytaj wartości",
    phExported: "Zapisano wartości: {count}",
    phImported: "Wczytano do pól: {filled} z {total}",
    snExportAll: "Eksport snippetów",
    snImportAll: "Import snippetów",
    snExported: "Wyeksportowano snippety: {count}",
    snImported: "Import: {added} nowych, {updated} nadpisanych",
    importBadFile: "To nie jest plik z tej aplikacji (JSON).",
    metadataPanel: "Metadane",
    metadataIntro: "Właściwości pliku z docProps/core.xml — widoczne w Eksploratorze / Wordzie, nie w treści dokumentu.",
    metadataTitleLabel: "Tytuł",
    metadataCreatorLabel: "Autor",
    metadataKeywordsLabel: "Słowa kluczowe",
    metadataReload: "Wczytaj z pliku",
    metadataApply: "Zastosuj",
    metadataHint: "Edytuj pola i kliknij Zastosuj, aby zapisać w pliku.",
    metadataSynced: "Zgodne z plikiem",
    metadataDirty: "Niezapisane zmiany metadanych",
    metadataApplied: "Metadane zapisane w pliku",
    filePanel: "Plik",
    viewPanel: "Widok",
    zoomLabel: "Powiększenie",
    zoomFit: "Dopasuj do ekranu",
    zoomReflowHint: "Widok mobilny: bez podziału na strony, nagłówków i stopek — zapis pliku bez zmian.",
    viewLayoutLabel: "Widok",
    viewLayoutBtnAria: "Powiększenie i widok (mobilny / desktopowy)",
    viewLayoutAuto: "Auto",
    viewLayoutAutoDesc: "Teraz: {view}",
    viewLayoutMobile: "Widok mobilny",
    viewLayoutMobileDesc: "Tekst zawija się do ekranu, palce zmieniają wielkość liter",
    viewLayoutDesktop: "Widok desktopowy",
    viewLayoutDesktopDesc: "Strony jak na wydruku, przybliżanie jak zdjęcie",
    viewLayoutRemembered: "Zapamiętane dla: {ctx}",
    viewCtxTouchPortrait: "ekran dotykowy w pionie",
    viewCtxTouchLandscape: "ekran dotykowy w poziomie",
    viewCtxDesktop: "komputer",
    viewAutoTip: "{view} — zmienisz go stuknięciem w procent na pasku",
    pinchToPages: "Puść — Widok desktopowy",
    showPageBreaks: "Granice stron (Widok desktopowy)",
    pageBreaksHint: "Przybliżone — Word może przenieść linijkę lub dwie na inną stronę.",
    pageBreakLabel: "str. {n}",
    dropText: "Przeciągnij plik",
    dropOr: "lub kliknij tutaj",
    dropBtn: "Wybierz plik",
    openFile: "Otwórz plik",
    emptyTitle: "Otwórz dokument .docx, .pdf albo zdjęcie dokumentu",
    emptyPdfBeta: "Zamiana PDF → .docx jest w wersji testowej — po konwersji sprawdź wynik.",
    emptySub: "Plik zostaje na tym urządzeniu — nic nie jest wysyłane na serwer.",
    loadSample: "Przykład",
    save: "Zapisz",
    saveAs: "Zapisz jako",
    // ── klawiatura, tryb skupienia (paczka E) ──
    skipToDoc: "Przejdź do dokumentu",
    docRegionAria: "Dokument",
    focusModeAria: "Tryb skupienia",
    focusModeExitAria: "Wyjdź z trybu skupienia",
    focusModeMenu: "Tryb skupienia",
    focusModeMenuExit: "Wyjdź z trybu skupienia",
    focusModeOn: "Tryb skupienia — Esc albo ten sam przycisk, żeby wyjść",
    focusModeOnTouch: "Tryb skupienia — ten sam przycisk przywraca widok",
    fullscreenMenu: "Pełny ekran",
    fullscreenMenuExit: "Wyjdź z pełnego ekranu",
    fullscreenFailed: "Przeglądarka nie pozwoliła na pełny ekran — został tryb skupienia",
    helpKeysTitle: "Klawiatura",
    helpKeysText: "Ctrl/⌘+F — szukaj · Enter / Shift+Enter (albo F3) — następne / poprzednie · Ctrl/⌘+S — zapisz · Ctrl/⌘+Enter — podział strony · Ctrl/⌘+Alt+N — nowy dokument · Ctrl/⌘+Alt+E — Czytanie ⇄ Edycja · Ctrl/⌘+Alt+F — tryb skupienia · Ctrl/⌘+Alt+1 / 2 / 3 — panel / pasek / dokument (F6 — po kolei) · Esc — krok wstecz",
    // ── Cofnij / Ponów (undo.js) ──
    undoGroupAria: "Cofnij i ponów",
    helpUndoTitle: "Cofnij / Ponów",
    helpUndoText: "Ctrl/⌘+Z — cofnij · Ctrl/⌘+Shift+Z lub Ctrl+Y — ponów · przyciski ↶ ↷ na pasku. Cofa operacje z panelu, formatowanie i pisanie (ciągłe pisanie = jeden krok, przerwa lub kliknięcie zaczyna nowy).",
    undoLabel: "Cofnij (Ctrl/⌘+Z)",
    redoLabel: "Ponów (Ctrl/⌘+Shift+Z)",
    undoWhat: "Cofnij: {what} (Ctrl/⌘+Z)",
    redoWhat: "Ponów: {what} (Ctrl/⌘+Shift+Z)",
    undoDone: "Cofnięto: {what}",
    redoDone: "Przywrócono: {what}",
    undoNothing: "Nie ma czego cofnąć",
    redoNothing: "Nie ma czego ponowić",
    undoWorking: "Cofam…",
    redoWorking: "Ponawiam…",
    undoFailed: "Nie udało się cofnąć — szczegóły w Logu",
    undoOpTyping: "pisanie",
    undoOpFormat: "formatowanie",
    undoOpReplace: "zamiana tekstu",
    undoOpCase: "wielkość liter",
    undoOpTrim: "spacje",
    undoOpAffix: "prefiks / sufiks",
    undoOpParagraphs: "zmiana akapitów",
    undoOpMetadata: "metadane",
    undoOpPlaceholders: "wypełnienie pól",
    undoOpSnippets: "rozwinięcie snippetów",
    undoOpEdit: "zmiana",
    // ── rama ekranu (paczka B, app-frame.js) ──
    heroSave: "Zapisz zmiany w pliku (Ctrl/⌘+S)",
    heroSaveDirty: "Zapisz — {changes}",
    statusUnsaved: "niezapisane: {changes}",
    changesOne: "1 zmiana",
    changesFew: "{n} zmiany",
    changesMany: "{n} zmian",
    appMenuAria: "Menu aplikacji: język, motyw, odświeżenie",
    menuLang: "Język",
    menuTheme: "Motyw",
    themeAria: "Zmień motyw jasny / ciemny",
    menuRefresh: "Odśwież aplikację",
    menuOtherApps: "Inne aplikacje",
    heroGripAria: "Zwiń lub rozwiń nagłówek",
    finderPlaceholder: "Znajdź ustawienie…",
    finderClear: "Wyczyść",
    finderEmpty: "Nic nie pasuje — spróbuj innego słowa.",
    groupFile: "Plik",
    groupEdit: "Edycja",
    groupTemplates: "Szablony",
    groupNav: "Nawigacja",
    groupView: "Widok",
    groupHelp: "Pomoc",
    frSearchInToolbar: "Szukaną frazę wpisujesz w polu nad dokumentem (Enter, ↑ ↓). Tu: zamiana i opcje.",
    showSectionChips: "Skróty sekcji nad dokumentem",
    searchPlaceholder: "Szukaj w dokumencie…",
    toolsAria: "Narzędzia (panel)",
    modeAria: "Tryb pracy z dokumentem",
    modeRead: "Czytanie",
    modeEdit: "Edycja",
    zoomOut: "Pomniejsz",
    zoomIn: "Powiększ",
    sectionStripHide: "Schowaj skróty sekcji (włączysz je w Widok)",
    sectionStripHidden: "Skróty sekcji schowane — włączysz je w panelu Widok",
    emptyOpen: "Wybierz plik z dysku",
    emptySample: "Wypróbuj na przykładowym dokumencie",
    emptyDropHint: "albo przeciągnij plik .docx, .pdf lub zdjęcie kartki w dowolne miejsce okna — PDF i zdjęcie zamienią się w edytowalny .docx",
    dropHere: "Upuść plik .docx, .pdf lub zdjęcie, żeby go otworzyć",
    metaWords: "{n} słów",
    metaParas: "{n} akapitów",
    metaInPlace: "zapis w miejscu",
    metaSaveAs: "zapis jako nowy plik",
    updateApp: "Aktualizuj",
    reloadUnsavedWarn: "Masz niezapisane zmiany. Aktualizacja przeładuje aplikację i te zmiany przepadną.\n\nAnuluj — wróć i najpierw zapisz.\nOK — aktualizuj bez zapisywania.",
    updateWaitsForSave: "Nowa wersja aplikacji jest gotowa. Zapisz zmiany, a potem kliknij „Aktualizuj”.",
    updateAvailable: "Jest nowa wersja aplikacji — kliknij „Aktualizuj”",
    refreshingApp: "Odświeżam…",
    cacheRefresh: "Odświeżam aplikację…",
    closeDocWarn: "Masz niezapisane zmiany. Zamknąć dokument?",
    closeDocAria: "Zamknij dokument",
    docClosed: "Dokument zamknięty",
    docTabsAria: "Otwarte dokumenty",
    docTabAdd: "Otwórz kolejny dokument",
    docTabClose: "Zamknij: {name}",
    docTabUnsaved: "niezapisane zmiany",
    docTabNotLoaded: "jeszcze nie wczytany — stuknij, żeby otworzyć",
    docTabsLimit: "Otwartych jest już {n} dokumentów — zamknij któryś, żeby otworzyć kolejny.",
    docTabsAdded: "Otwarto {n} dokumenty — przełączaj się kartami nad dokumentem.",
    docTabsAddedMany: "Otwarto {n} dokumentów — przełączaj się kartami nad dokumentem.",
    docTabAlready: "„{name}” jest już otwarty — przełączono na niego.",
    docTabSwitchFailed: "Nie udało się otworzyć „{name}”.",
    closeDoc: "Zamknij dokument",
    introAria: "Intro Mateusza",
    groupData: "Dane",
    groupTools: "Analiza i edycja",
    searchScopeAll: "Wszystko",
    searchScopeHeadings: "Nagłówki",
    grammarPanel: "Korekta",
    grammarLangLabel: "Język",
    grammarNbspLabel: "Twarde spacje (PL)",
    grammarScan: "Skanuj dokument",
    grammarApplyOne: "Zastosuj",
    grammarApplyAll: "Zastosuj wszystkie",
    grammarApplyRule: "Zastosuj regułę",
    grammarClear: "Wyczyść",
    grammarNoHits: "Brak sugestii korekty",
    grammarFound: "Znaleziono: {hits} ({rules} reguły)",
    grammarApplyAllConfirm: "Zastosować poprawki w {count} akapitach?",
    grammarAppliedOne: "Zastosowano poprawkę",
    grammarRuleDoubleSpace: "Podwójne spacje",
    grammarRuleSpaceBeforePunct: "Spacja przed interpunkcją",
    grammarRuleEllipsis: "Wielokropek",
    grammarRuleQuotesPl: "Cudzysłowy polskie",
    grammarRuleCapAfterPeriod: "Wielka litera po kropce",
    grammarRuleNbspPl: "Twarde spacje po przyimkach",
    placeholdersPanel: "Placeholdery",
    placeholdersScan: "Skanuj pola",
    placeholdersFill: "Wypełnij",
    placeholdersClear: "Wyczyść",
    placeholdersNoFields: "Brak pól {{…}} w dokumencie",
    placeholdersFound: "Znaleziono {count} pól ({total} wystąpień)",
    placeholdersFillConfirm: "Wypełnić {count} pól w dokumencie?",
    placeholdersApplied: "Wypełniono {count} wystąpień",
    placeholdersFieldLabel: "Pole",
    placeholdersEmptyValues: "Wpisz wartości w co najmniej jedno pole",
    placeholdersHint: "Samodzielne pola {{nazwa}} — wpisz w dokumencie lub użyj „Wstaw {{pole}}”, potem Skanuj → Wypełnij. Nie wymagają snippetów.",
    placeholdersInsertLabel: "Nazwa pola",
    placeholdersInsert: "Wstaw {{pole}}",
    placeholdersInsertInvalid: "Podaj nazwę pola (litery, cyfry, _, -, .)",
    placeholdersInserted: "Wstawiono {token}",
    helpPanel: "Skróty i informacje",
    helpPhTitle: "Placeholdery {{pole}}",
    helpPhIntro: "Szablony z polami do wypełnienia — bez ręcznego szukania w tekście.",
    helpPhItem1: "Składnia: {{nazwa}} — litery, cyfry, _, -, . (spacje w nawiasach są OK)",
    helpPhItem2: "Skanuj pola → wpisz wartości → Wypełnij → Zapisz",
    helpPhItem3: "Puste pola w formularzu są pomijane",
    helpPhItem4: "Ten sam {{pole}} w wielu miejscach — jedna wartość wszędzie",
    helpPhItem5: "Przykład: Umowa z {{imie}} {{nazwisko}}, data {{data}}.",
    helpPhItem6: "Opcjonalnie po snippetach: najpierw Rozwiń !snippety, potem Wypełnij {{placeholdery}}",
    helpPhItem7: "Panel Placeholdery → Wstaw {{pole}} wstawia token w kursorze",
    helpSnTitle: "Snippety !nazwa",
    helpSnIntro: "Wstawiane bloki tekstu — bezpieczniejsze z prefiksem ! niż zwykłe słowo.",
    helpSnItem1: "W dokumencie wpisz !testowysnippet + spacja — przy trybie Auto rozwija się od razu",
    helpSnItem2: "Snippet może zawierać {{placeholdery}} — rozwiń snippet, potem wypełnij pola",
    helpSnItem3: "Zapisz własny snippet w panelu, użyj Wstaw !trigger lub wpisz ręcznie",
    helpSnItem4: "Tryb ręczny: Skanuj → Rozwiń w dokumencie · Tryb auto: po !nazwa + spacja/interpunkcja",
    helpSnItem5: "Dynamiczne tokeny w treści: {date} {time} {datetime} {day} (jak Raycast)",
    fmtFontSizeLabel: "Rozmiar czcionki",
    fmtFontSizeInherit: "Jak w akapicie",
    selPartialTable: "Zaznaczenie obejmuje część tabeli i tekst obok niej — zaznacz całą tabelę albo tylko tekst poza nią.",
    undoOpCut: "wycięcie",
    insertFootnote: "Przypis dolny",
    insertFootnoteDesc: "Numer w tekście, treść na dole strony",
    insertEndnote: "Przypis końcowy",
    insertEndnoteDesc: "Numer w tekście, treść na końcu dokumentu",
    noteInNote: "Przypisu nie da się wstawić w treści przypisu — ustaw kursor w tekście dokumentu.",
    undoOpNote: "przypis",
    pageSetup: "Układ strony…",
    pageSetupDesc: "Marginesy, orientacja, rozmiar papieru",
    pageMargins: "Marginesy",
    marginNormal: "Normalne",
    marginNarrow: "Wąskie",
    marginModerate: "Umiarkowane",
    marginWide: "Szerokie",
    marginAll: "{v} cm ze wszystkich stron",
    marginTBLR: "Góra i dół {tb} cm · lewy i prawy {lr} cm",
    marginCustom: "Marginesy niestandardowe…",
    marginCurrent: "Teraz: G {t} · D {b} · L {l} · P {r} cm",
    marginCustomTitle: "Marginesy (cm)",
    margin_top: "Górny",
    margin_bottom: "Dolny",
    margin_left: "Lewy",
    margin_right: "Prawy",
    marginScope: "Zastosuj do",
    marginScopeAll: "Cały dokument",
    marginScopeSection: "Ta sekcja",
    marginApply: "Zastosuj",
    marginBad: "Wpisz liczby (cm), np. 2,5.",
    marginTooBig: "Za duże marginesy — na tekst zostałoby mniej niż 2,54 cm.",
    marginPrinterWarn: "Margines poniżej 0,64 cm: wiele drukarek nie drukuje tak blisko krawędzi — tekst może zostać ucięty.",
    pageOrient: "Orientacja",
    orientPortrait: "Pionowa",
    orientLandscape: "Pozioma",
    pageSize: "Rozmiar",
    undoOpPageSetup: "układ strony",
    pageSetupMobileHint: "Zmienione. Widok mobilny dopasowuje tekst do ekranu — marginesy i strony zobaczysz w Widoku desktopowym albo w Podglądzie wydruku (Ctrl/⌘+P).",
    hideWhiteSpace: "Ukryj biały obszar między stronami",
    commentReadOnlyNote: "Odpowiedzi i zmiany — w trybie Edycja.",
    pageGapHint: "Przerwa między stronami. Dwuklik — ukryj biały obszar (jak w Wordzie).",
    pageSeamHint: "Granica stron. Dwuklik — pokaż marginesy i przerwę między stronami.",
    ppMenu: "Podgląd wydruku…",
    ppMargins: "Marginesy",
    pageSetupMenu: "Marginesy i układ strony…",
    ppTitle: "Podgląd wydruku",
    ppClose: "Wróć",
    ppPages: "{n} str. · tak wyjdzie z drukarki",
    ppPageOf: "{n} / {total}",
    ppZone: "Strefa poza zasięgiem drukarki",
    ppZoneHint: "Pas {mm} mm przy krawędziach kartki — większość drukarek tam nie drukuje. Tekst w tym pasie może zostać ucięty.",
    ppPrint: "Drukuj…",
    ppWarn: "Str. {pages}: treść bliżej niż {mm} mm od krawędzi kartki — wiele drukarek jej nie wydrukuje (zostanie ucięta). Zwiększ marginesy, np. Wstaw → Układ strony → Wąskie (1,27 cm).",
    ppBuilding: "Układam strony do druku…",
    ppFail: "Nie udało się przygotować podglądu wydruku.",
    fmtFontFamilyLabel: "Czcionka",
    fontSizeOtherOpt: "Inny…",
    fontSizeOther: "Rozmiar czcionki w punktach (1–1638, np. 10,5):",
    fontFamilyOther: "Nazwa czcionki (np. Verdana):",
    fontOther: "Inna czcionka…",
    fontGroupDoc: "W tym dokumencie",
    fontGroupCommon: "Popularne",
    fontMixed: "różne czcionki ({n})",
    snippetsPanel: "Snippety",
    snippetsHint: "Wpisz w dokumencie „!” — pojawi się lista snippetów (↑ ↓, Enter/Tab). Nazwa może mieć polskie litery.",
    snippetsNameLabel: "Nazwa (w dokumencie: !nazwa)",
    snippetsBodyLabel: "Treść bloku",
    snippetsSave: "Zapisz snippet",
    snippetsInsert: "Wstaw treść",
    snippetsInsertTrigger: "Wstaw !trigger",
    snippetsExpandModeLabel: "Rozwijanie w edycji",
    snippetsExpandManual: "Ręcznie (przycisk Rozwiń)",
    snippetsExpandAuto: "Auto po !nazwa + spacja lub interpunkcja",
    snippetsExpandModeSaved: "Zapisano tryb rozwijania snippetów",
    snippetsAutoExpanded: "Rozwinięto {name}",
    snippetsTriggerInserted: "Wstawiono trigger {name}",
    snippetsDynamicHint: "W treści: {date} {date:short} {date:iso} {date+14:short} {time} {day} {month} {year}, {cursor} — tu stanie kursor, {{pole}} — zapyta o wartość ({{termin:data}} kalendarz, {{status:lista=A|B}} lista; „＋ Pole” zrobi to za Ciebie, także jako pole formularza Worda), !inny — snippet w snippecie. Nowa linia = łamanie wiersza.",
    snippetsScan: "Skanuj !triggery",
    snippetsExpand: "Rozwiń w dokumencie",
    snippetsUse: "Użyj",
    snippetsDelete: "Usuń",
    snippetsEmpty: "Brak zapisanych snippetów",
    snippetsNoTriggers: "Brak !triggerów w dokumencie",
    snippetsFound: "Znaleziono {count} triggerów ({total}×)",
    snippetsFoundMissing: "Znaleziono {count} triggerów ({total}×), brak definicji: {missing}",
    snippetsSaveInvalid: "Podaj nazwę (litera na początku) i treść snippetu",
    snippetsSaved: "Zapisano {name}",
    snippetsDeleteConfirm: "Usunąć snippet {name}?",
    snippetsExpandConfirm: "Rozwinąć {count} snippetów w dokumencie?",
    snippetsExpanded: "Rozwinięto {count} wystąpień",
    snippetsNothingToExpand: "Brak rozpoznanych !triggerów z definicją",
    snippetsInsertEmpty: "Brak treści snippetu",
    snippetsInsertNoCaret: "Ustaw kursor w akapicie w trybie edycji",
    snippetsInserted: "Wstawiono snippet",
    helpEditTitle: "Edycja w podglądzie",
    helpFrTitle: "Znajdź i zamień",
    helpFrText: "Skanuj trafienia przed zamianą; „Zamień bieżące” lub „Zamień wszystkie”.",
    helpGrammarTitle: "Korekta",
    helpGrammarText: "Offline — podwójne spacje, interpunkcja, cudzysłowy PL i inne reguły typografii.",
    // tworzenie dokumentu (docx-compose.js, compose-ui.js)
    insertMenu: "Wstaw",
    pageLayoutBtn: "Układ",
    insertGroupPage: "Strona",
    insertGroupText: "Tekst",
    insertGroupChars: "Znaki specjalne",
    insertPageBreak: "Podział strony",
    insertPageBreakDesc: "dalszy tekst od nowej strony",
    insertHrule: "Linia pozioma",
    insertHruleDesc: "kreska przez całą szerokość",
    insertDate: "Dzisiejsza data",
    insertNoCaret: "Kliknij w tekst dokumentu w trybie Edycja — tam trafi wstawiany element",
    paraStyleLabel: "Styl akapitu",
    styleNormal: "Normalny",
    styleTitle: "Tytuł",
    styleSubtitle: "Podtytuł",
    styleH1: "Nagłówek 1",
    styleH2: "Nagłówek 2",
    styleH3: "Nagłówek 3",
    styleQuote: "Cytat",
    styleCallout: "Ramka",
    fontGrow: "Zwiększ czcionkę",
    fontShrink: "Zmniejsz czcionkę",
    alignLabel: "Wyrównanie",
    alignLeft: "Do lewej",
    alignCenter: "Do środka",
    alignRight: "Do prawej",
    alignBoth: "Wyjustuj",
    undoOpParaFormat: "formatowanie akapitu",
    undoOpPageBreak: "podział strony",
    undoOpHrule: "linia pozioma",
    undoOpInsert: "wstawienie",
    emptyNew: "Nowy dokument",
    newDocMenu: "Nowy dokument…",
    photoDoc: "Zdjęcie dokumentu",
    newDocTitle: "Nowy dokument",
    newDocClose: "Zamknij",
    newDocBlank: "Pusty dokument",
    newDocBlankDesc: "Kartka A4, od zera",
    newDocLetter: "Pismo",
    newDocLetterDesc: "Nadawca, odbiorca, data, podpis — pola {{…}} do wypełnienia",
    newDocNote: "Notatka / raport",
    newDocNoteDesc: "Tytuł i nagłówki — gotowy spis sekcji",
    newDocFoot: "Plik powstaje na tym urządzeniu. „Zapisz” zapyta, gdzie go zapisać.",
    newDocFileBlank: "Nowy dokument",
    newDocFileLetter: "Pismo",
    newDocFileNote: "Notatka",
    newDocCreated: "Nowy dokument — pisz od razu. „Zapisz” nada mu nazwę i miejsce.",
    newDocFailed: "Nie udało się utworzyć dokumentu",
    insertLink: "Link…",
    insertLinkDesc: "adres WWW albo miejsce w dokumencie",
    linkTitle: "Link",
    linkText: "Tekst linku",
    linkTabWeb: "Adres WWW",
    linkTabDoc: "Miejsce w dokumencie",
    linkUrlPlaceholder: "np. example.com albo adres e-mail",
    linkNoHeadings: "Brak nagłówków i obrazów — nadaj akapitowi styl nagłówka albo wstaw obraz, żeby do niego linkować.",
    linkGroupHeadings: "Nagłówki",
    linkGroupImages: "Obrazy",
    linkImageN: "Obraz {n}",
    linkPeekGo: "Klik — przejdź do obrazu",
    linkPeekGoTouch: "Stuknij link — przejdź do obrazu",
    linkPeekZoom: "Powiększ",
    linkPeekZoomHint: "Podgląd obrazu bez przechodzenia (Spacja albo Shift+klik w link)",
    linkInsert: "Wstaw link",
    linkSave: "Zapisz",
    linkCancel: "Anuluj",
    linkRemove: "Usuń link",
    linkOpen: "Otwórz link (Ctrl/⌘+klik)",
    linkEdit: "Zmień link (Ctrl/⌘+K)",
    linkBadUrl: "Wpisz adres strony (np. example.com) albo e-mail — albo wybierz miejsce w dokumencie",
    linkToPlace: "→ {label}",
    undoOpLink: "link",
    listLabel: "Lista",
    listBullet: "Lista punktowana",
    listNumber: "Lista numerowana",
    listNone: "Bez listy",
    listLevel: "Poziom punktu (Tab / Shift+Tab)",
    listIndent: "Głębiej",
    listOutdent: "Płycej",
    listNotInList: "Kursor nie stoi w punkcie listy",
    undoOpList: "lista",
    insertGroupDoc: "Dokument",
    insertGroupForm: "Pole formularza",
    tocInsert: "Spis treści",
    tocInsertDesc: "z nagłówków 1–3, z linkami",
    tocUpdate: "Zaktualizuj spis treści",
    tocUpdateDesc: "nagłówki i numery stron od nowa",
    tocTitle: "Spis treści",
    tocEmpty: "Brak nagłówków — nadaj akapitom styl „Nagłówek 1–3” i zaktualizuj spis.",
    tocInserted: "Spis treści wstawiony. W Wordzie numery stron odświeżysz: prawy klik na spisie → Aktualizuj pole.",
    tocUpdated: "Spis treści zaktualizowany",
    undoOpToc: "spis treści",
    formInsertText: "Tekst",
    formInsertList: "Lista wyboru",
    formInsertDate: "Data",
    formInsertCheck: "Pole wyboru",
    formListOptions: "Pozycje listy — każda w osobnym wierszu",
    formListPlaceholder: "np.\nSprzedaż\nMarketing\nIT",
    formListEmpty: "Wpisz przynajmniej jedną pozycję",
    formInsertBtn: "Wstaw pole",
    undoOpFormInsert: "pole formularza",
    insertTable: "Tabela",
    insertTableDesc: "wybierz rozmiar z siatki",
    insertTablePick: "Wybierz rozmiar",
    insertTableCells: "{cols} kolumn × {rows} wierszy",
    insertImage: "Obraz…",
    insertImageDesc: "z dysku, aparatu albo zdjęć (lub wklej)",
    tableTools: "Tabela",
    tableNoCaret: "Kliknij w komórkę tabeli",
    tableInsertGroup: "Wstaw",
    tableDeleteGroup: "Usuń",
    tableRowAbove: "Wiersz powyżej",
    tableRowBelow: "Wiersz poniżej",
    tableColLeft: "Kolumna z lewej",
    tableColRight: "Kolumna z prawej",
    tableDelRow: "Usuń wiersz",
    tableDelCol: "Usuń kolumnę",
    tableDelTable: "Usuń tabelę",
    tableTabHint: "Tab — następna komórka (w ostatniej: nowy wiersz), Shift+Tab — poprzednia.",
    tableAlignGroup: "Wyrównanie w komórce",
    tableAlignScope: "Zakres wyrównania",
    tableScopeCell: "Komórka",
    tableScopeRow: "Wiersz",
    tableScopeCol: "Kolumna",
    tableScopeTable: "Tabela",
    cellAlignV_top: "Do góry",
    cellAlignV_center: "Do środka w pionie",
    cellAlignV_bottom: "Do dołu",
    cellAlignH_left: "do lewej",
    cellAlignH_center: "do środka",
    cellAlignH_right: "do prawej",
    pageVAlign: "Wyrównanie strony w pionie",
    pageVAlignDesc: "Góra, środek, wyjustuj, dół — np. strona tytułowa",
    pageVAlignTop: "Do góry (domyślne)",
    pageVAlignCenter: "Do środka",
    pageVAlignBoth: "Wyjustuj (rozłóż akapity na całą stronę)",
    pageVAlignBottom: "Do dołu",
    pageVAlignNote: "Dotyczy sekcji z kursorem. W podglądzie widać w Widoku desktopowym (strony).",
    undoOpTable: "tabela",
    imageTools: "Obraz",
    imageSize: "Szerokość obrazu (% szerokości tekstu)",
    imageAlt: "Tekst alternatywny",
    imageAltHelp: "Opis obrazu dla czytników ekranu i gdy obraz się nie wyświetli",
    imageDelete: "Usuń obraz (Delete)",
    imageView: "Podgląd obrazu — przybliżanie, pół / cały ekran (także dwuklik w obraz)",
    ivTitle: "Podgląd obrazu",
    ivCount: "Obraz {n} z {total}",
    ivPrev: "Poprzedni obraz (←)",
    ivNext: "Następny obraz (→)",
    ivZoomIn: "Przybliż (+)",
    ivZoomOut: "Oddal (−)",
    ivFit: "Dopasuj do okna (0)",
    ivActual: "Rzeczywisty rozmiar — piksel obrazu na piksel ekranu (1)",
    ivModeHalf: "Pół ekranu — podgląd obok dokumentu",
    ivModeFull: "Całe okno",
    ivFullscreen: "Pełny ekran (F)",
    ivFullscreenExit: "Wyjdź z pełnego ekranu (F)",
    ivDownload: "Zapisz obraz na urządzeniu",
    ivClose: "Zamknij podgląd (Esc)",
    ivHintMouse: "Kółko — przybliż · przeciągnij — przesuń · dwuklik — przybliż / dopasuj",
    ivHintTouch: "Rozsuń palce — przybliż · przeciągnij — przesuń · stuknij dwa razy — przybliż / dopasuj",
    ivFileWord: "obraz",
    ivSplit: "Granica podglądu — przeciągnij, by zmniejszyć lub powiększyć (strzałki)",
    imageBadType: "Tego pliku nie da się wstawić jako obraz",
    undoOpImage: "obraz",
    colorLabel: "Kolor czcionki i wyróżnienie",
    colorFont: "Kolor czcionki",
    colorAuto: "Automatyczny",
    colorMore: "Więcej kolorów…",
    colorHighlight: "Wyróżnienie tekstu",
    colorNoHighlight: "Bez wyróżnienia",
    colLighter: "{name}, jaśniejszy {pct}%",
    colDarker: "{name}, ciemniejszy {pct}%",
    colWhite: "Biały", colBlack: "Czarny", colLightGray: "Jasnoszary", colBlueGray: "Niebieskoszary", colBlue: "Niebieski",
    colOrange: "Pomarańczowy", colGray: "Szary", colGold: "Złoty", colLightBlue: "Jasnoniebieski", colGreen: "Zielony",
    colDarkRed: "Ciemnoczerwony", colRed: "Czerwony", colYellow: "Żółty", colLightGreen: "Jasnozielony", colDarkBlue: "Ciemnoniebieski",
    colPurple: "Fioletowy", colBrightGreen: "Jaskrawozielony", colTurquoise: "Turkusowy", colPink: "Różowy", colTeal: "Morski",
    colDarkGreen: "Ciemnozielony", colViolet: "Fiolet",
    insertComment: "Komentarz",
    insertCommentDesc: "do zaznaczenia albo słowa pod kursorem",
    commentText: "Treść komentarza",
    commentReplyText: "Odpowiedź",
    commentAuthor: "Twoje imię (zapamiętane na tym urządzeniu)",
    commentAuthorPh: "np. Jan Kowalski",
    commentNeedAuthor: "Wpisz imię — będzie podpisem komentarza w Wordzie",
    commentAddBtn: "Dodaj komentarz",
    commentReply: "Odpowiedz",
    commentReplyBtn: "Odpowiedz",
    commentResolve: "Rozwiąż",
    commentReopen: "Otwórz ponownie",
    commentResolved: "Rozwiązany",
    commentDelete: "Usuń",
    commentCard: "Komentarz",
    commentEdit: "Edytuj komentarz",
    commentEditTitle: "Edytuj komentarz",
    commentEditBlocked: "Tego komentarza nie da się tu edytować bez utraty treści (ma link, pole, wzmiankę albo inne formatowanie) — popraw go w Wordzie",
    commentMore: "Więcej",
    commentFmtHint: "Pogrubienie, kursywa, podkreślenie: przyciski B I U na pasku albo Ctrl/⌘+B, I, U",
    undoOpComment: "komentarz",
    hfInsert: "Nagłówek, stopka, numer strony…",
    hfInsertDesc: "na każdej stronie dokumentu",
    hfTitle: "Nagłówek i stopka",
    hfHeader: "Nagłówek (u góry każdej strony)",
    hfFooter: "Stopka (na dole każdej strony)",
    hfHeaderPh: "np. nazwa firmy albo tytuł",
    hfFooterPh: "np. Poufne",
    hfNumber: "Numer strony (w stopce)",
    hfNumNone: "Bez numeru",
    hfNumN: "1",
    hfNumPage: "Strona 1",
    hfNumPageOf: "Strona 1 z 5",
    hfNumDash: "– 1 –",
    hfFirst: "Inna pierwsza strona (bez nagłówka i stopki — np. strona tytułowa)",
    hfComplex: "Obecny nagłówek/stopka z Worda ma grafikę lub tabelę — zapis zastąpi je tekstem stąd.",
    hfSections: "Dokument ma {n} sekcje — zmiana dotyczy wszystkich.",
    hfWordUpdates: "Numery stron liczy Word; w podglądzie są szacunkowe.",
    undoOpHeaderFooter: "nagłówek i stopka",
    mergeAcross: "Tych akapitów nie da się skleić — są w różnych miejscach (komórka tabeli, pole na cały akapit).",
  },
  en: {
    locale: "en-US",
    title: "Documents Workbench",
    description: "Local viewing, editing, and analysis of Word documents",
    online: "Online",
    offline: "Offline",
    panelOpen: "Close panel",
    panelClosed: "Panel",
    noFile: "No file",
    loadingGeneric: "Loading…",
    loadingFile: "Loading document…",
    renderingDoc: "Rendering document…",
    savingFile: "Saving…",
    docLoaded: "Document loaded",
    sampleLoaded: "Sample document loaded",
    unsupportedType: "Supported formats: .docx, .pdf and photos of documents (.jpg, .png, .heic) — a PDF or photo becomes .docx",
    photoPreparing: "Preparing the photo ({n})…",
    photoDecodeFailed: "The photo could not be read — save it as JPG or PNG and try again.",
    photoHeicUnsupported: "This browser cannot read HEIC photos (iPhone). Save the photo as JPG (or open it in Safari) and try again.",
    photoPagesShort: "pp.",
    pdfSoon: "PDF is not supported yet — open a .docx file.",
    docOldFormat: "This is the old .doc format — in Word use “Save as” → Word Document (.docx) and open that file.",
    libsMissingStatus: "Document libraries missing",
    libsMissingToast: "Could not load DOCX libraries",
    noFileToSave: "Load a document first",
    saveDone: "Document saved",
    saveFailed: "Could not save file",
    saveAsPrompt: "File name",
    saveInPlaceWarn: "Save changes to the original file “{name}”? (Next “Save” won't ask again.)",
    saveDifferentFileWarn: "Selected file is “{name}”, not the current document. Overwrite anyway?",
    saveCancelled: "Save cancelled",
    draftTitle: "Unsaved work",
    draftChangedAt: "changed {when}",
    draftChanges: "changes: {count}",
    draftToday: "today at {time}",
    draftYesterday: "yesterday at {time}",
    draftRestore: "Restore",
    draftDiscard: "Discard",
    draftDiscardConfirm: "Delete the unsaved changes in “{name}”? This can't be undone.",
    draftRestored: "Restored unsaved work: {name}. Save it so you don't lose it.",
    draftGone: "That draft is no longer there.",
    draftRestoreFailed: "Couldn't restore the draft.",
    draftOriginalChanged: "“{name}” on disk changed since the draft — “Save” will create a copy so nothing gets overwritten.",
    draftNote: "The draft stays only on this device and disappears after 7 days.",
    draftMore: "Other unsaved work ({count})",
    linkBack: "↩ Back (Alt+←)",
    linkTargetMissing: "That place isn't in the document (bookmark removed or in another file).",
    linkUnsupported: "This link can't be opened here (local file or unsupported address) — open it in Word.",
    openExternalFailed: "Couldn't open the passed file — open it with the “Open” button.",
    saveDownloaded: "“{name}” downloaded — find it in Downloads (on iPhone: Files → Downloads).",
    savePickFileHint: "Select the .docx file you want to overwrite",
    savePermissionDenied: "No permission to save in place",
    editApplied: "Changes applied: {count}",
    editNothing: "No changes to apply",
    editErrNoFind: "Enter search text",
    editErrBadRegex: "Invalid regular expression",
    editErrNoAffix: "Enter a prefix or suffix",
    editToolNoChange: "No changes to apply",
    editOpLabel: "Operation",
    editOpReplace: "Find & replace",
    editOpCase: "Change case",
    editOpTrim: "Trim / spaces",
    editOpAffix: "Prefix / suffix",
    editCaseLabel: "Letter case",
    editCaseUpper: "UPPERCASE",
    editCaseLower: "lowercase",
    editCaseTitle: "Title Case",
    editTrimLabel: "Mode",
    editTrimEnds: "Trim ends",
    editTrimCollapse: "Collapse spaces",
    editTrimHard: "Replace hard spaces",
    editPrefixLabel: "Prefix (prepend)",
    editSuffixLabel: "Suffix (append)",
    inlineEditHint: "Enter — paragraph · Shift+Enter — line · Backspace — merge · Tab — list · Ctrl+Tab — heading · Ctrl+B/I/U — style · font size from list (inherits from paragraph)",
    searchNoMatches: "No matches",
    searchMatches: "{count} matches",
    readModeOn: "Read-only",
    readModeOff: "Edit mode",
    words: "Words",
    chars: "Characters",
    headings: "Headings",
    paragraphs: "Paragraphs",
    tables: "Tables",
    editToolsPanel: "Edit tools",
    editFindLabel: "Find",
    editReplaceLabel: "Replace with",
    editRegexLabel: "Regular expression",
    editScopeLabel: "Scope",
    editScopeAll: "Whole document",
    editScopeBody: "Main body",
    applyEdit: "Apply",
    searchPanel: "Search",
    frMatchCase: "Match case",
    frWholeWord: "Whole words only",
    frRegexHint: "In “Replace with”: $1, $2… = groups in parentheses, $& = whole match.",
    frScopeLabel: "Search in",
    frScopeAll: "All text",
    frScopeHeadings: "Section headings only",
    frOtherPartsLabel: "“Replace all” also in headers, footers and notes",
    frOtherFoundOn: "+{count} in headers, footers, notes (will be replaced too)",
    frOtherFoundOff: "+{count} in headers, footers, notes (tick the option to replace them too)",
    frReplaceAllOther: "Plus {count} in headers, footers and notes.",
    frListMore: "…and {count} more (use ↑ ↓)",
    grammarRescanned: "The text changed since the scan — suggestions refreshed, click again.",
    snippetsFieldsTitle: "Fill in the fields: {name}",
    snippetsFieldsHint: "Empty fields stay in the text as {{field}} — you can fill them later in the Placeholders panel. Values are remembered for next time.",
    snippetsFieldsInsert: "Insert",
    snippetsAddField: "＋ Field (calendar, list…)",
    snippetsFieldTitle: "Snippet field",
    snippetsFieldName: "Field name",
    snippetsFieldType: "Type",
    snippetsFieldTypeText: "Text",
    snippetsFieldTypeLong: "Multi-line text",
    snippetsFieldTypeNumber: "Number",
    snippetsFieldTypeDate: "Date (calendar)",
    snippetsFieldTypeList: "Drop-down list",
    snippetsFieldTypeCheck: "Check box ☐ / ☒",
    snippetsFieldTypeYesNo: "Yes / No",
    snippetsFieldOptions: "List items (one per line)",
    snippetsFieldDateFormat: "Date format",
    snippetsFieldDateShort: "04.10.2026",
    snippetsFieldDateLong: "4 October 2026",
    snippetsFieldDateIso: "2026-10-04",
    snippetsFieldForm: "Insert as a Word form field (filled in later in the document, also in Word)",
    snippetsFieldFormHint: "Without it: inserting the snippet shows a small window (calendar, list…) and the chosen value goes into the document.",
    snippetsFieldAdd: "Add to text",
    snippetsFieldNameMissing: "Enter a field name.",
    snippetsFieldListMissing: "Enter at least one list item.",
    snippetsSuggestHint: "↑ ↓ choose · Enter/Tab insert · Esc close",
    snippetsStarter: "Add example snippets",
    snippetsStarterAdded: "Example snippets added: {count}",
    snippetsFilter: "Find a snippet…",
    snippetsInsertShort: "Insert",
    snippetsEdit: "Edit",
    snippetsUpdated: "Updated {name}",
    cancel: "Cancel",
    undoOpSnippet: "snippet",
    frPanel: "Find & replace",
    frPrev: "Previous",
    frNext: "Next",
    frScan: "Find",
    frReplaceOne: "Replace current",
    frReplaceAll: "Replace all",
    frMatchPos: "Match {pos} / {total}",
    frPreviewOnly: "Save preview: {hits} hits in {paras} paragraphs",
    frReplaceAllConfirm: "Replace {hits} occurrences in {paras} paragraphs?",
    frReplacedOne: "Replaced current match",
    searchQueryLabel: "Query",
    searchScopeLabel: "Scope",
    searchHighlight: "Highlight",
    structurePanel: "Structure",
    structureFilterLabel: "Show",
    structureFilterAll: "All",
    structureFilterHeadings: "Headings",
    structureFilterParagraphs: "Paragraphs",
    structureFilterTables: "Tables",
    structureTypeHeading: "Head.",
    structureTypeParagraph: "Para.",
    structureTypeTable: "Table",
    structureCopy: "Copy",
    structureEdit: "Edit",
    structureQuickEditLabel: "Quick paragraph edit",
    structureQuickApply: "Apply",
    structureQuickFocus: "Edit in preview",
    structureCopied: "Text copied",
    structureCopyFailed: "Could not copy",
    structureNoOutline: "No elements in document",
    structureNoFilterMatch: "No elements in this filter",
    structureEmptyPara: "(empty paragraph)",
    structureTablePreview: "Table {rows}×{cols}: {preview}",
    structureTableEmpty: "Table {rows}×{cols}",
    structureOutlineTruncated: "Showing {shown} of {total} items",
    structureSearchLabel: "Search structure",
    structureSearchPlaceholder: "phrase in heading or paragraph…",
    structurePageSizeLabel: "Per page",
    structurePageInfo: "{start}–{end} of {total} · page {page}/{pages}",
    structurePrevPage: "Previous",
    structureNextPage: "Next",
    structureSearchNoMatch: "No search matches",
    lockTracked: "This paragraph has tracked changes — accept or reject them in the Review panel to edit it.",
    lockNote: "This note reference sits in an unusual place (e.g. inside a link) — editing here would lose it. Edit this paragraph in Word.",
    lockPageBreakOnly: "Page break. Delete it as in Word: Backspace at the start of the next paragraph or Delete at the end of the previous one.",
    pageBreakOnlyLabel: "Page break",
    lockPageBreak: "This paragraph has a page break inside — editing here would turn it into a plain line break. Edit it in Word.",
    lockNoteText: "This note contains something editing here would not keep (e.g. a table, field or tracked change) — edit it in Word.",
    noteHintJumpRead: "Click — go to the note",
    noteHintJumpEdit: "Double-click — go to the note and edit it",
    lockObject: "This paragraph contains an image or object — editing here would lose it. Edit it in Word.",
    lockSymbol: "This paragraph contains a Word symbol (e.g. from the Symbol font) mixed with text — editing here would lose it. Edit it in Word.",
    lockField: "This paragraph contains a field (e.g. page number, table of contents) — editing here would lose it.",
    lockLink: "This paragraph contains a link — editing here would lose it. Edit it in Word.",
    reviewPanel: "Review",
    reviewAuthorLabel: "Change author",
    reviewAcceptAllBtn: "Accept all",
    reviewRejectAllBtn: "Reject all",
    reviewAcceptAll: "Accept all",
    reviewRejectAll: "Reject all",
    reviewAcceptAuthor: "Accept: {author}",
    reviewRejectAuthor: "Reject: {author}",
    reviewAllAuthors: "All authors ({count})",
    reviewChangesHead: "Tracked changes",
    reviewCommentsHead: "Comments",
    reviewNotesHead: "Notes",
    reviewRemoveComments: "Delete all comments",
    reviewPreviewHint: "The preview shows the text as if changes were accepted (deletions are hidden). The list shows everything.",
    reviewSummary: "Changes: {changes} (authors: {authors}) · comments: {comments} · notes: {notes}",
    reviewNoChanges: "No tracked changes.",
    reviewNoComments: "No comments.",
    reviewNoNotes: "No footnotes or endnotes.",
    reviewShowMore: "Show the rest ({count})",
    reviewKindIns: "Inserted",
    reviewKindDel: "Deleted",
    reviewKindMoveFrom: "Moved from",
    reviewKindMoveTo: "Moved here",
    reviewKindFormat: "Formatting",
    reviewKindParaFormat: "Paragraph format",
    reviewKindOtherFormat: "Other layout change",
    reviewKindParaIns: "New paragraph",
    reviewKindParaDel: "Paragraphs joined",
    reviewKindRowIns: "Inserted row",
    reviewKindRowDel: "Deleted row",
    reviewInHeader: "in header",
    reviewInFooter: "in footer",
    reviewInFootnote: "in footnote",
    reviewInEndnote: "in endnote",
    reviewFootnote: "Footnote",
    reviewEndnote: "Endnote",
    reviewResolved: "resolved",
    reviewAcceptOne: "Accept change",
    reviewRejectOne: "Reject change",
    reviewDeleteComment: "Delete comment",
    reviewAcceptConfirm: "Accept changes ({count})?",
    reviewRejectConfirm: "Reject changes ({count})?",
    reviewRemoveCommentsConfirm: "Delete all comments ({count}) from the file?",
    reviewAccepted: "Accepted: {count}",
    reviewRejected: "Rejected: {count}",
    reviewCommentsRemoved: "Comments deleted: {count}",
    reviewOnOpen: "The document has tracked changes ({changes}) and comments ({comments}) — see the Review panel.",
    undoOpReview: "review",
    undoOpForm: "form field",
    lockForm: "This paragraph contains a Word form field — click the field to fill it in (or use the Form panel). The rest of the paragraph can't be edited here, or the field would break.",
    formsPanel: "Form",
    formsOnOpen: "This document is a Word form ({count} fields) — click a field in the document or open the Form panel.",
    formsSummary: "Fields: {count} · to fill in: {empty}",
    formsNone: "This document has no Word form fields (lists, dates, check boxes).",
    formsProtected: "The author protected this document in Word: only filling in fields is allowed.",
    formsShade: "Highlight fields in the document",
    formsHint: "Lists, dates, check boxes and text fields from Word. Click a field in the document or change it here — the form keeps working in Word.",
    formsKindCheckbox: "check box",
    formsKindDropdown: "list",
    formsKindCombo: "list or text",
    formsKindDate: "date",
    formsKindText: "text",
    formsLegacy: "legacy field",
    formsCopies: "in {count} places",
    formsLockedShort: "locked",
    formsLocked: "This field is locked in Word — its content can't be changed.",
    formsJump: "Show the field in the document",
    formsToday: "Today",
    formsUnnamed: "Unnamed field",
    undoOpInsert: "insert",
    undoOpPaste: "paste",
    exportPanel: "Export",
    exportIntro: "Download the document text (with your edits) as plain text, Markdown or HTML. All local.",
    exportPrint: "Print / save as PDF",
    exportPrintHint: "In the print dialog choose “Save as PDF”. Page layout as in the preview.",
    exportEmpty: "The document has no text to export.",
    exportDone: "Saved {name}",
    exportPrintFail: "Could not open the print dialog.",
    statsPanel: "Statistics",
    statsWords: "Words",
    statsChars: "Characters",
    statsCharsNoSpaces: "Characters (no spaces)",
    statsSentences: "Sentences",
    statsParagraphs: "Paragraphs",
    statsTables: "Tables",
    statsReading: "Reading time",
    statsAvgSentence: "Words per sentence",
    statsUnderMinute: "< 1 min",
    statsMinutes: "{n} min",
    statsTopWords: "Most frequent words",
    statsNoRepeats: "No repeated words (4+ letters).",
    statsLongLimit: "Long sentence = more than (words)",
    statsLongHead: "Longest sentences",
    statsNoLong: "No sentences over the threshold.",
    statsWordsShort: "{n} words",
    statsRefresh: "Refresh",
    statsSelectionHint: "Select text in the document to see its statistics.",
    statsSelection: "Selection: {words} words · {chars} characters · reading {min}",
    metadataScrub: "Remove personal data",
    metadataScrubConfirm: "Clear author, last modified by, description and subject in the file?",
    metadataScrubbed: "Personal data removed from metadata.",
    metadataScrubNothing: "Metadata was already clean.",
    phExportValues: "Save values (JSON)",
    phImportValues: "Load values",
    phExported: "Saved values: {count}",
    phImported: "Loaded into fields: {filled} of {total}",
    snExportAll: "Export snippets",
    snImportAll: "Import snippets",
    snExported: "Exported snippets: {count}",
    snImported: "Import: {added} new, {updated} overwritten",
    importBadFile: "This is not a file from this app (JSON).",
    metadataPanel: "Metadata",
    metadataIntro: "File properties from docProps/core.xml — shown in Explorer / Word, not in document body.",
    metadataTitleLabel: "Title",
    metadataCreatorLabel: "Author",
    metadataKeywordsLabel: "Keywords",
    metadataReload: "Reload from file",
    metadataApply: "Apply",
    metadataHint: "Edit fields and click Apply to save into the file.",
    metadataSynced: "Matches file",
    metadataDirty: "Unsaved metadata changes",
    metadataApplied: "Metadata saved to file",
    filePanel: "File",
    viewPanel: "View",
    zoomLabel: "Zoom",
    zoomFit: "Fit to screen",
    zoomReflowHint: "Mobile view: no page breaks, headers or footers — the saved file stays unchanged.",
    viewLayoutLabel: "View",
    viewLayoutBtnAria: "Zoom and view (mobile / desktop)",
    viewLayoutAuto: "Auto",
    viewLayoutAutoDesc: "Now: {view}",
    viewLayoutMobile: "Mobile view",
    viewLayoutMobileDesc: "Text wraps to the screen, fingers change the text size",
    viewLayoutDesktop: "Desktop view",
    viewLayoutDesktopDesc: "Pages as printed, zoom like a photo",
    viewLayoutRemembered: "Remembered for: {ctx}",
    viewCtxTouchPortrait: "touch screen, portrait",
    viewCtxTouchLandscape: "touch screen, landscape",
    viewCtxDesktop: "computer",
    viewAutoTip: "{view} — change it by tapping the percentage in the toolbar",
    pinchToPages: "Release — Desktop view",
    showPageBreaks: "Page boundaries (Desktop view)",
    pageBreaksHint: "Approximate — Word may move a line or two to another page.",
    pageBreakLabel: "p. {n}",
    dropText: "Drop a file",
    dropOr: "or click here",
    dropBtn: "Choose file",
    openFile: "Open file",
    emptyTitle: "Open a .docx or .pdf document, or a photo of a document",
    emptyPdfBeta: "PDF → .docx conversion is in testing — please check the result after converting.",
    emptySub: "Your file stays on this device — nothing is uploaded to a server.",
    loadSample: "Sample",
    save: "Save",
    saveAs: "Save as",
    // ── keyboard, focus mode (package E) ──
    skipToDoc: "Skip to the document",
    docRegionAria: "Document",
    focusModeAria: "Focus mode",
    focusModeExitAria: "Exit focus mode",
    focusModeMenu: "Focus mode",
    focusModeMenuExit: "Exit focus mode",
    focusModeOn: "Focus mode — press Esc or the same button to exit",
    focusModeOnTouch: "Focus mode — the same button brings the view back",
    fullscreenMenu: "Full screen",
    fullscreenMenuExit: "Exit full screen",
    fullscreenFailed: "The browser refused full screen — focus mode is on",
    helpKeysTitle: "Keyboard",
    helpKeysText: "Ctrl/⌘+F — search · Enter / Shift+Enter (or F3) — next / previous · Ctrl/⌘+S — save · Ctrl/⌘+Enter — page break · Ctrl/⌘+Alt+N — new document · Ctrl/⌘+Alt+E — Reading ⇄ Editing · Ctrl/⌘+Alt+F — focus mode · Ctrl/⌘+Alt+1 / 2 / 3 — panel / toolbar / document (F6 — in turn) · Esc — step back",
    // ── Undo / Redo (undo.js) ──
    undoGroupAria: "Undo and redo",
    helpUndoTitle: "Undo / Redo",
    helpUndoText: "Ctrl/⌘+Z — undo · Ctrl/⌘+Shift+Z or Ctrl+Y — redo · ↶ ↷ buttons in the toolbar. Undoes panel operations, formatting and typing (continuous typing = one step; a pause or a click starts a new one).",
    undoLabel: "Undo (Ctrl/⌘+Z)",
    redoLabel: "Redo (Ctrl/⌘+Shift+Z)",
    undoWhat: "Undo: {what} (Ctrl/⌘+Z)",
    redoWhat: "Redo: {what} (Ctrl/⌘+Shift+Z)",
    undoDone: "Undone: {what}",
    redoDone: "Redone: {what}",
    undoNothing: "Nothing to undo",
    redoNothing: "Nothing to redo",
    undoWorking: "Undoing…",
    redoWorking: "Redoing…",
    undoFailed: "Undo failed — details in the Log",
    undoOpTyping: "typing",
    undoOpFormat: "formatting",
    undoOpReplace: "text replace",
    undoOpCase: "letter case",
    undoOpTrim: "spaces",
    undoOpAffix: "prefix / suffix",
    undoOpParagraphs: "paragraph changes",
    undoOpMetadata: "metadata",
    undoOpPlaceholders: "field fill",
    undoOpSnippets: "snippet expansion",
    undoOpEdit: "change",
    // ── screen frame (package B, app-frame.js) ──
    heroSave: "Save changes to the file (Ctrl/⌘+S)",
    heroSaveDirty: "Save — {changes}",
    statusUnsaved: "unsaved: {changes}",
    changesOne: "1 change",
    changesFew: "{n} changes",
    changesMany: "{n} changes",
    appMenuAria: "App menu: language, theme, refresh",
    menuLang: "Language",
    menuTheme: "Theme",
    themeAria: "Switch light / dark theme",
    menuRefresh: "Refresh the app",
    menuOtherApps: "Other apps",
    heroGripAria: "Collapse or expand the header",
    finderPlaceholder: "Find a setting…",
    finderClear: "Clear",
    finderEmpty: "Nothing matches — try another word.",
    groupFile: "File",
    groupEdit: "Editing",
    groupTemplates: "Templates",
    groupNav: "Navigation",
    groupView: "View",
    groupHelp: "Help",
    frSearchInToolbar: "Type the search phrase in the field above the document (Enter, ↑ ↓). Here: replace and options.",
    showSectionChips: "Section shortcuts above the document",
    searchPlaceholder: "Search the document…",
    toolsAria: "Tools (panel)",
    modeAria: "Document mode",
    modeRead: "Reading",
    modeEdit: "Editing",
    zoomOut: "Zoom out",
    zoomIn: "Zoom in",
    sectionStripHide: "Hide section shortcuts (turn them on in View)",
    sectionStripHidden: "Section shortcuts hidden — turn them on in the View panel",
    emptyOpen: "Choose a file",
    emptySample: "Try the sample document",
    emptyDropHint: "or drop a .docx, .pdf or a photo of a page anywhere in the window — a PDF or photo becomes an editable .docx",
    dropHere: "Drop the .docx, .pdf or photo to open it",
    metaWords: "{n} words",
    metaParas: "{n} paragraphs",
    metaInPlace: "saves in place",
    metaSaveAs: "saves as a new file",
    updateApp: "Update",
    reloadUnsavedWarn: "You have unsaved changes. Updating reloads the app and they will be lost.\n\nCancel — go back and save first.\nOK — update without saving.",
    updateWaitsForSave: "A new app version is ready. Save your changes, then click “Update”.",
    updateAvailable: "A new version is available — click “Update”",
    refreshingApp: "Refreshing…",
    cacheRefresh: "Refreshing the app…",
    closeDocWarn: "You have unsaved changes. Close the document?",
    closeDocAria: "Close document",
    docClosed: "Document closed",
    docTabsAria: "Open documents",
    docTabAdd: "Open another document",
    docTabClose: "Close: {name}",
    docTabUnsaved: "unsaved changes",
    docTabNotLoaded: "not loaded yet — tap to open",
    docTabsLimit: "{n} documents are already open — close one to open another.",
    docTabsAdded: "Opened {n} documents — switch with the tabs above the document.",
    docTabsAddedMany: "Opened {n} documents — switch with the tabs above the document.",
    docTabAlready: "“{name}” is already open — switched to it.",
    docTabSwitchFailed: "Could not open “{name}”.",
    closeDoc: "Close document",
    introAria: "Mateusz intro",
    groupData: "Data",
    groupTools: "Analysis & editing",
    searchScopeAll: "Everything",
    searchScopeHeadings: "Headings",
    grammarPanel: "Proofing",
    grammarLangLabel: "Language",
    grammarNbspLabel: "Hard spaces (PL)",
    grammarScan: "Scan document",
    grammarApplyOne: "Apply",
    grammarApplyAll: "Apply all",
    grammarApplyRule: "Apply rule",
    grammarClear: "Clear",
    grammarNoHits: "No proofing suggestions",
    grammarFound: "Found: {hits} ({rules} rules)",
    grammarApplyAllConfirm: "Apply fixes in {count} paragraphs?",
    grammarAppliedOne: "Fix applied",
    grammarRuleDoubleSpace: "Double spaces",
    grammarRuleSpaceBeforePunct: "Space before punctuation",
    grammarRuleEllipsis: "Ellipsis",
    grammarRuleQuotesPl: "Polish quotation marks",
    grammarRuleCapAfterPeriod: "Capital after period",
    grammarRuleNbspPl: "Hard spaces after prepositions",
    placeholdersPanel: "Placeholders",
    placeholdersScan: "Scan fields",
    placeholdersFill: "Fill in",
    placeholdersClear: "Clear",
    placeholdersNoFields: "No {{…}} fields in document",
    placeholdersFound: "Found {count} fields ({total} occurrences)",
    placeholdersFillConfirm: "Fill {count} fields in the document?",
    placeholdersApplied: "Filled {count} occurrences",
    placeholdersFieldLabel: "Field",
    placeholdersEmptyValues: "Enter a value in at least one field",
    placeholdersHint: "Standalone {{name}} fields — type in the document or use Insert {{field}}, then Scan → Fill. No snippets required.",
    placeholdersInsertLabel: "Field name",
    placeholdersInsert: "Insert {{field}}",
    placeholdersInsertInvalid: "Enter a valid field name (letters, digits, _, -, .)",
    placeholdersInserted: "Inserted {token}",
    helpPanel: "Shortcuts & tips",
    helpPhTitle: "Placeholders {{field}}",
    helpPhIntro: "Templates with fill-in fields — no manual search through the document.",
    helpPhItem1: "Syntax: {{name}} — letters, digits, _, -, . (spaces inside braces are OK)",
    helpPhItem2: "Scan fields → enter values → Fill in → Save",
    helpPhItem3: "Empty form fields are skipped",
    helpPhItem4: "Same {{field}} in many places — one value replaces all",
    helpPhItem5: "Example: Agreement with {{first_name}} {{last_name}}, date {{date}}.",
    helpPhItem6: "Optional with snippets: expand !snippets first, then Fill {{placeholders}}",
    helpPhItem7: "Placeholders panel → Insert {{field}} puts a token at the caret",
    helpSnTitle: "Snippets !name",
    helpSnIntro: "Insertable text blocks — the ! prefix avoids accidental matches.",
    helpSnItem1: "Type !testsnippet + space — in Auto mode it expands immediately",
    helpSnItem2: "A snippet may contain {{placeholders}} — expand snippet, then fill fields",
    helpSnItem3: "Save your own snippet in the panel; use Insert !trigger or type manually",
    helpSnItem4: "Manual: Scan → Expand in document · Auto: after !name + space or punctuation",
    helpSnItem5: "Dynamic tokens in body: {date} {time} {datetime} {day} (Raycast-style)",
    fmtFontSizeLabel: "Font size",
    fmtFontSizeInherit: "Match paragraph",
    selPartialTable: "The selection covers part of a table and text next to it — select the whole table or only the text outside it.",
    undoOpCut: "cut",
    insertFootnote: "Footnote",
    insertFootnoteDesc: "Number in the text, note at the bottom of the page",
    insertEndnote: "Endnote",
    insertEndnoteDesc: "Number in the text, note at the end of the document",
    noteInNote: "A note can’t be inserted inside a note — put the cursor in the document text.",
    undoOpNote: "note",
    pageSetup: "Page layout…",
    pageSetupDesc: "Margins, orientation, paper size",
    pageMargins: "Margins",
    marginNormal: "Normal",
    marginNarrow: "Narrow",
    marginModerate: "Moderate",
    marginWide: "Wide",
    marginAll: "{v} cm on all sides",
    marginTBLR: "Top and bottom {tb} cm · left and right {lr} cm",
    marginCustom: "Custom margins…",
    marginCurrent: "Now: T {t} · B {b} · L {l} · R {r} cm",
    marginCustomTitle: "Margins (cm)",
    margin_top: "Top",
    margin_bottom: "Bottom",
    margin_left: "Left",
    margin_right: "Right",
    marginScope: "Apply to",
    marginScopeAll: "Whole document",
    marginScopeSection: "This section",
    marginApply: "Apply",
    marginBad: "Enter numbers (cm), e.g. 2.5.",
    marginTooBig: "Margins too large — less than 2.54 cm would be left for text.",
    marginPrinterWarn: "Margin below 0.64 cm: many printers can’t print that close to the edge — text may be cut off.",
    pageOrient: "Orientation",
    orientPortrait: "Portrait",
    orientLandscape: "Landscape",
    pageSize: "Size",
    undoOpPageSetup: "page layout",
    pageSetupMobileHint: "Changed. The mobile view fits text to the screen — see margins and pages in the desktop view or the print preview (Ctrl/⌘+P).",
    hideWhiteSpace: "Hide white space between pages",
    commentReadOnlyNote: "Replies and changes — in Edit mode.",
    pageGapHint: "Gap between pages. Double-click — hide white space (as in Word).",
    pageSeamHint: "Page boundary. Double-click — show margins and the gap between pages.",
    ppMenu: "Print preview…",
    ppMargins: "Margins",
    pageSetupMenu: "Margins and page layout…",
    ppTitle: "Print preview",
    ppClose: "Back",
    ppPages: "{n} pages · this is what the printer gets",
    ppPageOf: "{n} / {total}",
    ppZone: "Area the printer can’t reach",
    ppZoneHint: "A {mm} mm band at the paper edges — most printers can’t print there. Text in it may be cut off.",
    ppPrint: "Print…",
    ppWarn: "Page {pages}: content closer than {mm} mm to the paper edge — many printers won’t print it (it gets cut off). Increase the margins, e.g. Insert → Page layout → Narrow (1.27 cm).",
    ppBuilding: "Laying out pages for printing…",
    ppFail: "Could not prepare the print preview.",
    fmtFontFamilyLabel: "Font",
    fontSizeOtherOpt: "Other…",
    fontSizeOther: "Font size in points (1–1638, e.g. 10.5):",
    fontFamilyOther: "Font name (e.g. Verdana):",
    fontOther: "Other font…",
    fontGroupDoc: "In this document",
    fontGroupCommon: "Common",
    fontMixed: "mixed fonts ({n})",
    snippetsPanel: "Snippets",
    snippetsHint: "Type “!” in the document — a list of snippets appears (↑ ↓, Enter/Tab). Names may use any letters.",
    snippetsNameLabel: "Name (in document: !name)",
    snippetsBodyLabel: "Block text",
    snippetsSave: "Save snippet",
    snippetsInsert: "Insert body",
    snippetsInsertTrigger: "Insert !trigger",
    snippetsExpandModeLabel: "Expand while editing",
    snippetsExpandManual: "Manual (Expand button)",
    snippetsExpandAuto: "Auto after !name + space or punctuation",
    snippetsExpandModeSaved: "Snippet expand mode saved",
    snippetsAutoExpanded: "Expanded {name}",
    snippetsTriggerInserted: "Inserted trigger {name}",
    snippetsDynamicHint: "In the body: {date} {date:short} {date:iso} {date+14:short} {time} {day} {month} {year}, {cursor} — caret goes here, {{field}} — asks for a value ({{due:date}} calendar, {{status:list=A|B}} list; “＋ Field” builds it for you, also as a Word form field), !other — snippet inside a snippet. New line = line break.",
    snippetsScan: "Scan !triggers",
    snippetsExpand: "Expand in document",
    snippetsUse: "Use",
    snippetsDelete: "Delete",
    snippetsEmpty: "No saved snippets",
    snippetsNoTriggers: "No !triggers in document",
    snippetsFound: "Found {count} triggers ({total}×)",
    snippetsFoundMissing: "Found {count} triggers ({total}×), missing definitions: {missing}",
    snippetsSaveInvalid: "Enter a valid name (starts with a letter) and body text",
    snippetsSaved: "Saved {name}",
    snippetsDeleteConfirm: "Delete snippet {name}?",
    snippetsExpandConfirm: "Expand {count} snippets in the document?",
    snippetsExpanded: "Expanded {count} occurrences",
    snippetsNothingToExpand: "No recognized !triggers with a saved definition",
    snippetsInsertEmpty: "Snippet body is empty",
    snippetsInsertNoCaret: "Place the caret in a paragraph in edit mode",
    snippetsInserted: "Snippet inserted",
    helpEditTitle: "Inline editing",
    helpFrTitle: "Find & replace",
    helpFrText: "Scan matches before replacing; Replace current or Replace all.",
    helpGrammarTitle: "Proofing",
    helpGrammarText: "Offline — double spaces, punctuation, Polish quotes, and other typography rules.",
    insertMenu: "Insert",
    pageLayoutBtn: "Layout",
    insertGroupPage: "Page",
    insertGroupText: "Text",
    insertGroupChars: "Special characters",
    insertPageBreak: "Page break",
    insertPageBreakDesc: "continue on a new page",
    insertHrule: "Horizontal line",
    insertHruleDesc: "a rule across the page",
    insertDate: "Today's date",
    insertNoCaret: "Click into the document text in Editing mode — that's where the item goes",
    paraStyleLabel: "Paragraph style",
    styleNormal: "Normal",
    styleTitle: "Title",
    styleSubtitle: "Subtitle",
    styleH1: "Heading 1",
    styleH2: "Heading 2",
    styleH3: "Heading 3",
    styleQuote: "Quote",
    styleCallout: "Box",
    fontGrow: "Grow font",
    fontShrink: "Shrink font",
    alignLabel: "Alignment",
    alignLeft: "Align left",
    alignCenter: "Center",
    alignRight: "Align right",
    alignBoth: "Justify",
    undoOpParaFormat: "paragraph formatting",
    undoOpPageBreak: "page break",
    undoOpHrule: "horizontal line",
    undoOpInsert: "insertion",
    emptyNew: "New document",
    newDocMenu: "New document…",
    photoDoc: "Photo of a document",
    newDocTitle: "New document",
    newDocClose: "Close",
    newDocBlank: "Blank document",
    newDocBlankDesc: "An A4 page, from scratch",
    newDocLetter: "Letter",
    newDocLetterDesc: "Sender, recipient, date, signature — {{…}} fields to fill in",
    newDocNote: "Note / report",
    newDocNoteDesc: "Title and headings — sections ready to go",
    newDocFoot: "The file is created on this device. Save will ask where to put it.",
    newDocFileBlank: "New document",
    newDocFileLetter: "Letter",
    newDocFileNote: "Note",
    newDocCreated: "New document — start typing. Save gives it a name and a place.",
    newDocFailed: "Couldn't create the document",
    insertLink: "Link…",
    insertLinkDesc: "web address or a place in the document",
    linkTitle: "Link",
    linkText: "Link text",
    linkTabWeb: "Web address",
    linkTabDoc: "Place in document",
    linkUrlPlaceholder: "e.g. example.com or an e-mail address",
    linkNoHeadings: "No headings or images — give a paragraph a heading style or insert an image to link to it.",
    linkGroupHeadings: "Headings",
    linkGroupImages: "Images",
    linkImageN: "Image {n}",
    linkPeekGo: "Click — go to the image",
    linkPeekGoTouch: "Tap the link — go to the image",
    linkPeekZoom: "Enlarge",
    linkPeekZoomHint: "Preview the picture without going there (Space or Shift+click the link)",
    linkInsert: "Insert link",
    linkSave: "Save",
    linkCancel: "Cancel",
    linkRemove: "Remove link",
    linkOpen: "Open link (Ctrl/⌘+click)",
    linkEdit: "Edit link (Ctrl/⌘+K)",
    linkBadUrl: "Enter a web address (e.g. example.com) or e-mail — or pick a place in the document",
    linkToPlace: "→ {label}",
    undoOpLink: "link",
    listLabel: "List",
    listBullet: "Bulleted list",
    listNumber: "Numbered list",
    listNone: "No list",
    listLevel: "Item level (Tab / Shift+Tab)",
    listIndent: "Deeper",
    listOutdent: "Shallower",
    listNotInList: "The caret isn't in a list item",
    undoOpList: "list",
    insertGroupDoc: "Document",
    insertGroupForm: "Form field",
    tocInsert: "Table of contents",
    tocInsertDesc: "from headings 1–3, with links",
    tocUpdate: "Update table of contents",
    tocUpdateDesc: "rebuild headings and page numbers",
    tocTitle: "Contents",
    tocEmpty: "No headings — give paragraphs a Heading 1–3 style and update the table.",
    tocInserted: "Table of contents inserted. In Word, refresh page numbers: right-click the table → Update Field.",
    tocUpdated: "Table of contents updated",
    undoOpToc: "table of contents",
    formInsertText: "Text",
    formInsertList: "Drop-down list",
    formInsertDate: "Date",
    formInsertCheck: "Check box",
    formListOptions: "List items — one per line",
    formListPlaceholder: "e.g.\nSales\nMarketing\nIT",
    formListEmpty: "Enter at least one item",
    formInsertBtn: "Insert field",
    undoOpFormInsert: "form field",
    insertTable: "Table",
    insertTableDesc: "pick the size from the grid",
    insertTablePick: "Pick a size",
    insertTableCells: "{cols} columns × {rows} rows",
    insertImage: "Picture…",
    insertImageDesc: "from disk, camera or photos (or paste)",
    tableTools: "Table",
    tableNoCaret: "Click into a table cell",
    tableInsertGroup: "Insert",
    tableDeleteGroup: "Delete",
    tableRowAbove: "Row above",
    tableRowBelow: "Row below",
    tableColLeft: "Column left",
    tableColRight: "Column right",
    tableDelRow: "Delete row",
    tableDelCol: "Delete column",
    tableDelTable: "Delete table",
    tableTabHint: "Tab — next cell (in the last one: new row), Shift+Tab — previous.",
    tableAlignGroup: "Cell alignment",
    tableAlignScope: "Alignment scope",
    tableScopeCell: "Cell",
    tableScopeRow: "Row",
    tableScopeCol: "Column",
    tableScopeTable: "Table",
    cellAlignV_top: "Top",
    cellAlignV_center: "Middle",
    cellAlignV_bottom: "Bottom",
    cellAlignH_left: "left",
    cellAlignH_center: "center",
    cellAlignH_right: "right",
    pageVAlign: "Vertical page alignment",
    pageVAlignDesc: "Top, center, justified, bottom — e.g. a title page",
    pageVAlignTop: "Top (default)",
    pageVAlignCenter: "Center",
    pageVAlignBoth: "Justified (spread paragraphs over the page)",
    pageVAlignBottom: "Bottom",
    pageVAlignNote: "Applies to the section with the cursor. Visible in the preview in Desktop view (pages).",
    undoOpTable: "table",
    imageTools: "Picture",
    imageSize: "Picture width (% of text width)",
    imageAlt: "Alt text",
    imageAltHelp: "Describe the picture for screen readers and when it can't be shown",
    imageDelete: "Delete picture (Delete)",
    imageView: "Picture preview — zoom, half / full screen (or double-click the picture)",
    ivTitle: "Picture preview",
    ivCount: "Picture {n} of {total}",
    ivPrev: "Previous picture (←)",
    ivNext: "Next picture (→)",
    ivZoomIn: "Zoom in (+)",
    ivZoomOut: "Zoom out (−)",
    ivFit: "Fit to window (0)",
    ivActual: "Actual size — one image pixel per screen pixel (1)",
    ivModeHalf: "Half screen — preview next to the document",
    ivModeFull: "Whole window",
    ivFullscreen: "Full screen (F)",
    ivFullscreenExit: "Exit full screen (F)",
    ivDownload: "Save picture to device",
    ivClose: "Close preview (Esc)",
    ivHintMouse: "Wheel — zoom · drag — pan · double-click — zoom / fit",
    ivHintTouch: "Pinch — zoom · drag — pan · double-tap — zoom / fit",
    ivFileWord: "picture",
    ivSplit: "Preview edge — drag to make it smaller or larger (arrow keys)",
    imageBadType: "This file can't be inserted as a picture",
    undoOpImage: "picture",
    colorLabel: "Font color and highlight",
    colorFont: "Font color",
    colorAuto: "Automatic",
    colorMore: "More colors…",
    colorHighlight: "Text highlight",
    colorNoHighlight: "No highlight",
    colLighter: "{name}, lighter {pct}%",
    colDarker: "{name}, darker {pct}%",
    colWhite: "White", colBlack: "Black", colLightGray: "Light gray", colBlueGray: "Blue-gray", colBlue: "Blue",
    colOrange: "Orange", colGray: "Gray", colGold: "Gold", colLightBlue: "Light blue", colGreen: "Green",
    colDarkRed: "Dark red", colRed: "Red", colYellow: "Yellow", colLightGreen: "Light green", colDarkBlue: "Dark blue",
    colPurple: "Purple", colBrightGreen: "Bright green", colTurquoise: "Turquoise", colPink: "Pink", colTeal: "Teal",
    colDarkGreen: "Dark green", colViolet: "Violet",
    insertComment: "Comment",
    insertCommentDesc: "on the selection or the word at the caret",
    commentText: "Comment",
    commentReplyText: "Reply",
    commentAuthor: "Your name (remembered on this device)",
    commentAuthorPh: "e.g. Jane Smith",
    commentNeedAuthor: "Enter your name — it signs the comment in Word",
    commentAddBtn: "Add comment",
    commentReply: "Reply",
    commentReplyBtn: "Reply",
    commentResolve: "Resolve",
    commentReopen: "Reopen",
    commentResolved: "Resolved",
    commentDelete: "Delete",
    commentCard: "Comment",
    commentEdit: "Edit comment",
    commentEditTitle: "Edit comment",
    commentEditBlocked: "This comment can't be edited here without losing content (it has a link, field, mention or other formatting) — edit it in Word",
    commentMore: "More",
    commentFmtHint: "Bold, italic, underline: the B I U buttons on the toolbar or Ctrl/⌘+B, I, U",
    undoOpComment: "comment",
    hfInsert: "Header, footer, page number…",
    hfInsertDesc: "on every page of the document",
    hfTitle: "Header and footer",
    hfHeader: "Header (top of every page)",
    hfFooter: "Footer (bottom of every page)",
    hfHeaderPh: "e.g. company name or title",
    hfFooterPh: "e.g. Confidential",
    hfNumber: "Page number (in the footer)",
    hfNumNone: "No number",
    hfNumN: "1",
    hfNumPage: "Page 1",
    hfNumPageOf: "Page 1 of 5",
    hfNumDash: "– 1 –",
    hfFirst: "Different first page (no header and footer — e.g. a title page)",
    hfComplex: "The current Word header/footer has a picture or table — saving replaces it with the text here.",
    hfSections: "The document has {n} sections — the change applies to all of them.",
    hfWordUpdates: "Word counts the page numbers; in the preview they're estimates.",
    undoOpHeaderFooter: "header and footer",
    mergeAcross: "These paragraphs can't be joined — they live in different places (table cell, whole-paragraph field).",
  },
};

function t(key, vars) {
  const copy = I18N[currentLang][key] ?? I18N.pl[key] ?? key;
  if (!vars) return copy;
  return copy.replace(/\{(\w+)\}/g, (_, k) => (vars[k] != null ? String(vars[k]) : ""));
}

function applyLanguage() {
  const copy = I18N[currentLang];
  BASE_TITLE = copy.title;
  document.documentElement.lang = currentLang;
  const desc = document.getElementById("pageDescription");
  if (desc) desc.setAttribute("content", copy.description);
  if (!hasUnsavedChanges) document.title = copy.title;
  document.querySelectorAll("[data-i18n]").forEach((el) => {
    const key = el.dataset.i18n;
    if (copy[key]) el.textContent = copy[key];
  });
  document.querySelectorAll("[data-i18n-aria]").forEach((el) => {
    const key = el.dataset.i18nAria;
    if (copy[key]) el.setAttribute("aria-label", copy[key]);
  });
  document.querySelectorAll("[data-i18n-placeholder]").forEach((el) => {
    const key = el.dataset.i18nPlaceholder;
    if (copy[key]) el.placeholder = copy[key];
  });
  const introVid = document.getElementById("introVideo");
  if (introVid && copy.introAria) introVid.setAttribute("aria-label", copy.introAria);
  document.querySelectorAll(".lang-button").forEach((btn) => {
    const on = btn.dataset.lang === currentLang;
    btn.classList.toggle("is-active", on);
    btn.setAttribute("aria-pressed", on ? "true" : "false");
  });
  if (typeof syncLangSwitchPill === "function") syncLangSwitchPill();
  if (documentStructure && typeof renderStructurePanel === "function") renderStructurePanel(documentStructure);
  if (typeof appFrame !== "undefined") appFrame.onLanguageChange();
  if (typeof dwbUndo !== "undefined") dwbUndo.sync();
  if (typeof dwbView !== "undefined") dwbView.syncMenu();
  if (typeof syncViewLayoutUi === "function") syncViewLayoutUi();
  if (typeof dwbPageBreaks !== "undefined") dwbPageBreaks.schedule(0); // „str. N” / „p. N”
  if (typeof refreshFontFamilyList === "function") refreshFontFamilyList(); // grupy listy krojów
}

function setLanguage(lang) {
  currentLang = lang === "en" ? "en" : "pl";
  localStorage.setItem(LANG_KEY, currentLang);
  applyLanguage();
}
