// Language dictionaries and translation helpers.

let currentLang = localStorage.getItem(typeof LANG_KEY !== "undefined" ? LANG_KEY : "documents-workbench-lang") === "en" ? "en" : "pl";
let BASE_TITLE = document.title || "Documents Workbench";

const I18N = {
  pl: {
    locale: "pl-PL",
    title: "Documents Workbench",
    description: "Lokalne przeglądanie, edycja i analiza dokumentów Word",
    online: "Online",
    offline: "Offline",
    panelOpen: "Zamknij panel",
    panelClosed: "Panel",
    noFile: "Brak pliku",
    loadingGeneric: "Ładowanie…",
    loadingFile: "Wczytywanie dokumentu…",
    renderingDoc: "Renderowanie dokumentu…",
    savingFile: "Zapisywanie…",
    docLoaded: "Dokument wczytany",
    sampleLoaded: "Przykładowy dokument wczytany",
    unsupportedType: "Obsługiwane formaty: .docx (PDF wkrótce)",
    pdfSoon: "PDF nie jest jeszcze obsługiwany — otwórz plik .docx.",
    docOldFormat: "To stary format .doc — w Wordzie wybierz „Zapisz jako” → Dokument programu Word (.docx) i otwórz ten plik.",
    libsMissingStatus: "Brak bibliotek dokumentu",
    libsMissingToast: "Nie udało się wczytać bibliotek DOCX",
    noFileToSave: "Najpierw wczytaj dokument",
    saveDone: "Zapisano dokument",
    saveFailed: "Nie udało się zapisać pliku",
    saveAsPrompt: "Nazwa pliku",
    saveInPlaceWarn: "Nadpisać oryginalny plik?",
    saveDifferentFileWarn: "Wybrany plik to „{name}”, nie bieżący dokument. Nadpisać mimo to?",
    saveCancelled: "Anulowano zapis",
    savePickFileHint: "Wskaż plik .docx, który chcesz nadpisać",
    savePermissionDenied: "Brak uprawnień do zapisu w tym miejscu",
    editApplied: "Zastosowano zmiany: {count}",
    editNothing: "Brak zmian do zastosowania",
    editErrNoFind: "Podaj szukany tekst",
    editErrBadRegex: "Niepoprawne wyrażenie regularne",
    editErrNoAffix: "Podaj prefiks lub sufiks",
    editToolNoChange: "Brak zmian do zastosowania",
    editOpLabel: "Operacja",
    editOpReplace: "Znajdź i zamień",
    editOpCase: "Zmiana wielkości",
    editOpTrim: "Przytnij / spacje",
    editOpAffix: "Prefiks / sufiks",
    editCaseLabel: "Wielkość liter",
    editCaseUpper: "WIELKIE",
    editCaseLower: "małe",
    editCaseTitle: "Jak Nazwa Własna",
    editTrimLabel: "Tryb",
    editTrimEnds: "Przytnij końce",
    editTrimCollapse: "Zwiń wielokrotne spacje",
    editTrimHard: "Zamień twarde spacje",
    editPrefixLabel: "Prefiks (z przodu)",
    editSuffixLabel: "Sufiks (z tyłu)",
    inlineEditHint: "Enter — akapit · Shift+Enter — linia · Backspace — scal · Tab — lista · Ctrl+Tab — nagłówek · Ctrl+B/I/U — styl · rozmiar z listy (dziedziczy z akapitu)",
    searchNoMatches: "Brak trafień",
    searchMatches: "{count} trafień",
    readModeOn: "Tylko odczyt",
    readModeOff: "Tryb edycji",
    words: "Słowa",
    chars: "Znaki",
    headings: "Nagłówki",
    paragraphs: "Akapity",
    tables: "Tabele",
    editToolsPanel: "Narzędzia edycji",
    editFindLabel: "Szukaj",
    editReplaceLabel: "Zamień na",
    editRegexLabel: "Wyrażenie regularne",
    editScopeLabel: "Zakres",
    editScopeAll: "Cały dokument",
    editScopeBody: "Treść główna",
    applyEdit: "Zastosuj",
    searchPanel: "Wyszukiwanie",
    frMatchCase: "Rozróżniaj wielkość liter",
    frWholeWord: "Tylko całe słowa",
    frRegexHint: "W polu „Zamień na”: $1, $2… = grupy z nawiasów, $& = całe trafienie.",
    frScopeLabel: "Szukaj w",
    frScopeAll: "Cała treść",
    frScopeHeadings: "Tylko nagłówki sekcji",
    frOtherPartsLabel: "„Zamień wszystkie” także w nagłówkach, stopkach i przypisach",
    frOtherFoundOn: "+{count} w nagłówkach, stopkach, przypisach (też zostaną zamienione)",
    frOtherFoundOff: "+{count} w nagłówkach, stopkach, przypisach (zaznacz opcję, żeby je też zamienić)",
    frReplaceAllOther: "Oraz {count} w nagłówkach, stopkach i przypisach.",
    frListMore: "…i jeszcze {count} (przejdź ↑ ↓)",
    grammarRescanned: "Tekst zmienił się od skanu — sugestie odświeżone, kliknij jeszcze raz.",
    snippetsFieldsTitle: "Uzupełnij pola: {name}",
    snippetsFieldsHint: "Puste pole zostanie w tekście jako {{pole}} — możesz je wypełnić później w panelu Placeholdery.",
    snippetsFieldsInsert: "Wstaw",
    snippetsSuggestHint: "↑ ↓ wybór · Enter/Tab wstaw · Esc zamknij",
    snippetsStarter: "Dodaj przykładowe snippety",
    snippetsStarterAdded: "Dodano przykładowe snippety: {count}",
    snippetsFilter: "Szukaj snippetu…",
    snippetsInsertShort: "Wstaw",
    snippetsEdit: "Edytuj",
    snippetsUpdated: "Zaktualizowano {name}",
    cancel: "Anuluj",
    undoOpSnippet: "snippet",
    frPanel: "Znajdź i zamień",
    frPrev: "Poprzednie",
    frNext: "Następne",
    frScan: "Szukaj",
    frReplaceOne: "Zamień bieżące",
    frReplaceAll: "Zamień wszystkie",
    frMatchPos: "Trafienie {pos} / {total}",
    frPreviewOnly: "Podgląd zapisu: {hits} wystąpień w {paras} akapitach",
    frReplaceAllConfirm: "Zamienić {hits} wystąpień w {paras} akapitach?",
    frReplacedOne: "Zamieniono bieżące trafienie",
    searchQueryLabel: "Fraza",
    searchScopeLabel: "Zakres",
    searchHighlight: "Podświetl",
    structurePanel: "Struktura",
    structureFilterLabel: "Pokaż",
    structureFilterAll: "Wszystko",
    structureFilterHeadings: "Nagłówki",
    structureFilterParagraphs: "Akapity",
    structureFilterTables: "Tabele",
    structureTypeHeading: "Nagł.",
    structureTypeParagraph: "Akap.",
    structureTypeTable: "Tabela",
    structureCopy: "Kopiuj",
    structureEdit: "Edytuj",
    structureQuickEditLabel: "Szybka edycja akapitu",
    structureQuickApply: "Zastosuj",
    structureQuickFocus: "Edytuj w podglądzie",
    structureCopied: "Skopiowano tekst",
    structureCopyFailed: "Nie udało się skopiować",
    structureNoOutline: "Brak elementów w dokumencie",
    structureNoFilterMatch: "Brak elementów w tym filtrze",
    structureEmptyPara: "(pusty akapit)",
    structureTablePreview: "Tabela {rows}×{cols}: {preview}",
    structureTableEmpty: "Tabela {rows}×{cols}",
    structureOutlineTruncated: "Pokazano {shown} z {total} elementów",
    structureSearchLabel: "Szukaj w strukturze",
    structureSearchPlaceholder: "fraza w nagłówku lub akapicie…",
    structurePageSizeLabel: "Na stronie",
    structurePageInfo: "{start}–{end} z {total} · str. {page}/{pages}",
    structurePrevPage: "Poprzednia",
    structureNextPage: "Następna",
    structureSearchNoMatch: "Brak trafień wyszukiwania",
    lockTracked: "Akapit ma śledzone zmiany — zaakceptuj lub odrzuć je w panelu Recenzja, żeby go edytować.",
    lockNote: "Akapit ma odwołanie do przypisu — edycja tutaj by je zgubiła. Edytuj go w Wordzie.",
    lockObject: "Akapit zawiera obraz lub obiekt — edycja tutaj by go zgubiła. Edytuj go w Wordzie.",
    lockField: "Akapit zawiera pole (np. numer strony, spis treści) — edycja tutaj by je zgubiła.",
    lockLink: "Akapit zawiera link — edycja tutaj by go zgubiła. Edytuj go w Wordzie.",
    reviewPanel: "Recenzja",
    reviewAuthorLabel: "Autor zmian",
    reviewAcceptAllBtn: "Akceptuj wszystkie",
    reviewRejectAllBtn: "Odrzuć wszystkie",
    reviewAcceptAll: "Akceptuj wszystkie",
    reviewRejectAll: "Odrzuć wszystkie",
    reviewAcceptAuthor: "Akceptuj: {author}",
    reviewRejectAuthor: "Odrzuć: {author}",
    reviewAllAuthors: "Wszyscy autorzy ({count})",
    reviewChangesHead: "Śledzone zmiany",
    reviewCommentsHead: "Komentarze",
    reviewNotesHead: "Przypisy",
    reviewRemoveComments: "Usuń wszystkie komentarze",
    reviewPreviewHint: "Podgląd pokazuje tekst tak, jakby zmiany były już zaakceptowane (usunięć w nim nie widać). Lista obok pokazuje wszystko.",
    reviewSummary: "Zmiany: {changes} (autorzy: {authors}) · komentarze: {comments} · przypisy: {notes}",
    reviewNoChanges: "Brak śledzonych zmian.",
    reviewNoComments: "Brak komentarzy.",
    reviewNoNotes: "Brak przypisów.",
    reviewShowMore: "Pokaż pozostałe ({count})",
    reviewKindIns: "Wstawiono",
    reviewKindDel: "Usunięto",
    reviewKindMoveFrom: "Przeniesiono stąd",
    reviewKindMoveTo: "Przeniesiono tu",
    reviewKindFormat: "Formatowanie",
    reviewKindParaFormat: "Format akapitu",
    reviewKindOtherFormat: "Inna zmiana układu",
    reviewKindParaIns: "Nowy akapit",
    reviewKindParaDel: "Połączenie akapitów",
    reviewKindRowIns: "Wstawiony wiersz",
    reviewKindRowDel: "Usunięty wiersz",
    reviewInHeader: "w nagłówku",
    reviewInFooter: "w stopce",
    reviewInFootnote: "w przypisie",
    reviewInEndnote: "w przypisie końcowym",
    reviewFootnote: "Przypis",
    reviewEndnote: "Przypis końcowy",
    reviewResolved: "rozwiązany",
    reviewAcceptOne: "Akceptuj zmianę",
    reviewRejectOne: "Odrzuć zmianę",
    reviewDeleteComment: "Usuń komentarz",
    reviewAcceptConfirm: "Zaakceptować zmiany ({count})?",
    reviewRejectConfirm: "Odrzucić zmiany ({count})?",
    reviewRemoveCommentsConfirm: "Usunąć wszystkie komentarze ({count}) z pliku?",
    reviewAccepted: "Zaakceptowano: {count}",
    reviewRejected: "Odrzucono: {count}",
    reviewCommentsRemoved: "Usunięto komentarze: {count}",
    reviewOnOpen: "Dokument ma śledzone zmiany ({changes}) i komentarze ({comments}) — zobacz panel Recenzja.",
    undoOpReview: "recenzja",
    undoOpInsert: "wstawienie",
    undoOpPaste: "wklejenie",
    exportPanel: "Eksport",
    exportIntro: "Pobierz treść dokumentu (razem z Twoimi edycjami) jako tekst, Markdown lub HTML. Wszystko lokalnie.",
    exportPrint: "Drukuj / zapisz jako PDF",
    exportPrintHint: "W oknie druku wybierz „Zapisz jako PDF”. Układ stron jak w podglądzie.",
    exportEmpty: "Dokument nie ma tekstu do wyeksportowania.",
    exportDone: "Zapisano {name}",
    exportPrintFail: "Nie udało się otworzyć okna druku.",
    statsPanel: "Statystyki",
    statsWords: "Słowa",
    statsChars: "Znaki",
    statsCharsNoSpaces: "Znaki bez spacji",
    statsSentences: "Zdania",
    statsParagraphs: "Akapity",
    statsTables: "Tabele",
    statsReading: "Czas czytania",
    statsAvgSentence: "Słów na zdanie",
    statsUnderMinute: "< 1 min",
    statsMinutes: "{n} min",
    statsTopWords: "Najczęstsze słowa",
    statsNoRepeats: "Brak powtarzających się słów (4+ liter).",
    statsLongLimit: "Długie zdanie = więcej niż (słów)",
    statsLongHead: "Najdłuższe zdania",
    statsNoLong: "Brak zdań dłuższych niż ustalony próg.",
    statsWordsShort: "{n} słów",
    statsRefresh: "Odśwież",
    statsSelectionHint: "Zaznacz fragment w dokumencie, a zobaczysz jego statystyki.",
    statsSelection: "Zaznaczenie: {words} słów · {chars} znaków · czytanie {min}",
    metadataScrub: "Usuń dane osobowe",
    metadataScrubConfirm: "Wyczyścić autora, ostatnio zmieniającego, opis i temat w pliku?",
    metadataScrubbed: "Dane osobowe usunięte z metadanych.",
    metadataScrubNothing: "Metadane były już czyste.",
    phExportValues: "Zapisz wartości (JSON)",
    phImportValues: "Wczytaj wartości",
    phExported: "Zapisano wartości: {count}",
    phImported: "Wczytano do pól: {filled} z {total}",
    snExportAll: "Eksport snippetów",
    snImportAll: "Import snippetów",
    snExported: "Wyeksportowano snippety: {count}",
    snImported: "Import: {added} nowych, {updated} nadpisanych",
    importBadFile: "To nie jest plik z tej aplikacji (JSON).",
    metadataPanel: "Metadane",
    metadataIntro: "Właściwości pliku z docProps/core.xml — widoczne w Eksploratorze / Wordzie, nie w treści dokumentu.",
    metadataTitleLabel: "Tytuł",
    metadataCreatorLabel: "Autor",
    metadataKeywordsLabel: "Słowa kluczowe",
    metadataReload: "Wczytaj z pliku",
    metadataApply: "Zastosuj",
    metadataHint: "Edytuj pola i kliknij Zastosuj, aby zapisać w pliku.",
    metadataSynced: "Zgodne z plikiem",
    metadataDirty: "Niezapisane zmiany metadanych",
    metadataApplied: "Metadane zapisane w pliku",
    filePanel: "Plik",
    viewPanel: "Widok",
    zoomLabel: "Powiększenie",
    zoomFit: "Dopasuj do ekranu",
    zoomReset: "Układ strony",
    zoomReflowHint: "Tekst dopasowuje się do szerokości ekranu — zapis pliku bez zmian.",
    dropText: "Przeciągnij plik",
    dropOr: "lub kliknij tutaj",
    dropBtn: "Wybierz plik",
    openFile: "Otwórz plik",
    emptyTitle: "Otwórz dokument .docx",
    emptySub: "Plik zostaje na tym urządzeniu — nic nie jest wysyłane na serwer.",
    loadSample: "Przykład",
    save: "Zapisz",
    saveAs: "Zapisz jako",
    // ── klawiatura, tryb skupienia (paczka E) ──
    skipToDoc: "Przejdź do dokumentu",
    docRegionAria: "Dokument",
    focusModeAria: "Tryb skupienia",
    focusModeExitAria: "Wyjdź z trybu skupienia",
    focusModeMenu: "Tryb skupienia",
    focusModeMenuExit: "Wyjdź z trybu skupienia",
    focusModeOn: "Tryb skupienia — Esc albo ten sam przycisk, żeby wyjść",
    focusModeOnTouch: "Tryb skupienia — ten sam przycisk przywraca widok",
    fullscreenMenu: "Pełny ekran",
    fullscreenMenuExit: "Wyjdź z pełnego ekranu",
    fullscreenFailed: "Przeglądarka nie pozwoliła na pełny ekran — został tryb skupienia",
    helpKeysTitle: "Klawiatura",
    helpKeysText: "Ctrl/⌘+F — szukaj · Enter / Shift+Enter (albo F3) — następne / poprzednie · Ctrl/⌘+S — zapisz · Ctrl/⌘+Alt+E — Czytanie ⇄ Edycja · Ctrl/⌘+Alt+F — tryb skupienia · Ctrl/⌘+Alt+1 / 2 / 3 — panel / pasek / dokument (F6 — po kolei) · Esc — krok wstecz",
    // ── Cofnij / Ponów (undo.js) ──
    undoGroupAria: "Cofnij i ponów",
    helpUndoTitle: "Cofnij / Ponów",
    helpUndoText: "Ctrl/⌘+Z — cofnij · Ctrl/⌘+Shift+Z lub Ctrl+Y — ponów · przyciski ↶ ↷ na pasku. Cofa operacje z panelu, formatowanie i pisanie (ciągłe pisanie = jeden krok, przerwa lub kliknięcie zaczyna nowy).",
    undoLabel: "Cofnij (Ctrl/⌘+Z)",
    redoLabel: "Ponów (Ctrl/⌘+Shift+Z)",
    undoWhat: "Cofnij: {what} (Ctrl/⌘+Z)",
    redoWhat: "Ponów: {what} (Ctrl/⌘+Shift+Z)",
    undoDone: "Cofnięto: {what}",
    redoDone: "Przywrócono: {what}",
    undoNothing: "Nie ma czego cofnąć",
    redoNothing: "Nie ma czego ponowić",
    undoWorking: "Cofam…",
    redoWorking: "Ponawiam…",
    undoFailed: "Nie udało się cofnąć — szczegóły w Logu",
    undoOpTyping: "pisanie",
    undoOpFormat: "formatowanie",
    undoOpReplace: "zamiana tekstu",
    undoOpCase: "wielkość liter",
    undoOpTrim: "spacje",
    undoOpAffix: "prefiks / sufiks",
    undoOpParagraphs: "zmiana akapitów",
    undoOpMetadata: "metadane",
    undoOpPlaceholders: "wypełnienie pól",
    undoOpSnippets: "rozwinięcie snippetów",
    undoOpEdit: "zmiana",
    // ── rama ekranu (paczka B, app-frame.js) ──
    heroSave: "Zapisz zmiany w pliku (Ctrl/⌘+S)",
    heroSaveDirty: "Zapisz — {changes}",
    statusUnsaved: "niezapisane: {changes}",
    changesOne: "1 zmiana",
    changesFew: "{n} zmiany",
    changesMany: "{n} zmian",
    appMenuAria: "Menu aplikacji: język, motyw, odświeżenie",
    menuLang: "Język",
    menuTheme: "Motyw",
    themeAria: "Zmień motyw jasny / ciemny",
    menuRefresh: "Odśwież aplikację",
    menuOtherApps: "Inne aplikacje",
    heroGripAria: "Zwiń lub rozwiń nagłówek",
    finderPlaceholder: "Znajdź ustawienie…",
    finderClear: "Wyczyść",
    finderEmpty: "Nic nie pasuje — spróbuj innego słowa.",
    groupFile: "Plik",
    groupEdit: "Edycja",
    groupTemplates: "Szablony",
    groupNav: "Nawigacja",
    groupView: "Widok",
    groupHelp: "Pomoc",
    frSearchInToolbar: "Szukaną frazę wpisujesz w polu nad dokumentem (Enter, ↑ ↓). Tu: zamiana i opcje.",
    showSectionChips: "Skróty sekcji nad dokumentem",
    searchPlaceholder: "Szukaj w dokumencie…",
    toolsAria: "Narzędzia (panel)",
    modeAria: "Tryb pracy z dokumentem",
    modeRead: "Czytanie",
    modeEdit: "Edycja",
    zoomOut: "Pomniejsz",
    zoomFitShort: "Dopasuj",
    zoomIn: "Powiększ",
    sectionStripHide: "Schowaj skróty sekcji (włączysz je w Widok)",
    sectionStripHidden: "Skróty sekcji schowane — włączysz je w panelu Widok",
    emptyOpen: "Wybierz plik z dysku",
    emptySample: "Wypróbuj na przykładowym dokumencie",
    emptyDropHint: "albo przeciągnij plik .docx w dowolne miejsce okna",
    dropHere: "Upuść plik .docx, żeby go otworzyć",
    metaWords: "{n} słów",
    metaParas: "{n} akapitów",
    metaInPlace: "zapis w miejscu",
    metaSaveAs: "zapis jako nowy plik",
    updateApp: "Aktualizuj",
    updateAvailable: "Jest nowa wersja aplikacji — kliknij „Aktualizuj”",
    refreshingApp: "Odświeżam…",
    cacheRefresh: "Odświeżam aplikację…",
    closeDocWarn: "Masz niezapisane zmiany. Zamknąć dokument?",
    closeDocAria: "Zamknij dokument",
    docClosed: "Dokument zamknięty",
    closeDoc: "Zamknij dokument",
    introAria: "Intro Mateusza",
    groupData: "Dane",
    groupTools: "Analiza i edycja",
    searchScopeAll: "Wszystko",
    searchScopeHeadings: "Nagłówki",
    grammarPanel: "Korekta",
    grammarLangLabel: "Język",
    grammarNbspLabel: "Twarde spacje (PL)",
    grammarScan: "Skanuj dokument",
    grammarApplyOne: "Zastosuj",
    grammarApplyAll: "Zastosuj wszystkie",
    grammarApplyRule: "Zastosuj regułę",
    grammarClear: "Wyczyść",
    grammarNoHits: "Brak sugestii korekty",
    grammarFound: "Znaleziono: {hits} ({rules} reguły)",
    grammarApplyAllConfirm: "Zastosować poprawki w {count} akapitach?",
    grammarAppliedOne: "Zastosowano poprawkę",
    grammarRuleDoubleSpace: "Podwójne spacje",
    grammarRuleSpaceBeforePunct: "Spacja przed interpunkcją",
    grammarRuleEllipsis: "Wielokropek",
    grammarRuleQuotesPl: "Cudzysłowy polskie",
    grammarRuleCapAfterPeriod: "Wielka litera po kropce",
    grammarRuleNbspPl: "Twarde spacje po przyimkach",
    placeholdersPanel: "Placeholdery",
    placeholdersScan: "Skanuj pola",
    placeholdersFill: "Wypełnij",
    placeholdersClear: "Wyczyść",
    placeholdersNoFields: "Brak pól {{…}} w dokumencie",
    placeholdersFound: "Znaleziono {count} pól ({total} wystąpień)",
    placeholdersFillConfirm: "Wypełnić {count} pól w dokumencie?",
    placeholdersApplied: "Wypełniono {count} wystąpień",
    placeholdersFieldLabel: "Pole",
    placeholdersEmptyValues: "Wpisz wartości w co najmniej jedno pole",
    placeholdersHint: "Samodzielne pola {{nazwa}} — wpisz w dokumencie lub użyj „Wstaw {{pole}}”, potem Skanuj → Wypełnij. Nie wymagają snippetów.",
    placeholdersInsertLabel: "Nazwa pola",
    placeholdersInsert: "Wstaw {{pole}}",
    placeholdersInsertInvalid: "Podaj nazwę pola (litery, cyfry, _, -, .)",
    placeholdersInserted: "Wstawiono {token}",
    helpPanel: "Skróty i informacje",
    helpPhTitle: "Placeholdery {{pole}}",
    helpPhIntro: "Szablony z polami do wypełnienia — bez ręcznego szukania w tekście.",
    helpPhItem1: "Składnia: {{nazwa}} — litery, cyfry, _, -, . (spacje w nawiasach są OK)",
    helpPhItem2: "Skanuj pola → wpisz wartości → Wypełnij → Zapisz",
    helpPhItem3: "Puste pola w formularzu są pomijane",
    helpPhItem4: "Ten sam {{pole}} w wielu miejscach — jedna wartość wszędzie",
    helpPhItem5: "Przykład: Umowa z {{imie}} {{nazwisko}}, data {{data}}.",
    helpPhItem6: "Opcjonalnie po snippetach: najpierw Rozwiń !snippety, potem Wypełnij {{placeholdery}}",
    helpPhItem7: "Panel Placeholdery → Wstaw {{pole}} wstawia token w kursorze",
    helpSnTitle: "Snippety !nazwa",
    helpSnIntro: "Wstawiane bloki tekstu — bezpieczniejsze z prefiksem ! niż zwykłe słowo.",
    helpSnItem1: "W dokumencie wpisz !testowysnippet + spacja — przy trybie Auto rozwija się od razu",
    helpSnItem2: "Snippet może zawierać {{placeholdery}} — rozwiń snippet, potem wypełnij pola",
    helpSnItem3: "Zapisz własny snippet w panelu, użyj Wstaw !trigger lub wpisz ręcznie",
    helpSnItem4: "Tryb ręczny: Skanuj → Rozwiń w dokumencie · Tryb auto: po !nazwa + spacja/interpunkcja",
    helpSnItem5: "Dynamiczne tokeny w treści: {date} {time} {datetime} {day} (jak Raycast)",
    fmtFontSizeLabel: "Rozmiar czcionki",
    fmtFontSizeInherit: "Jak w akapicie",
    snippetsPanel: "Snippety",
    snippetsHint: "Wpisz w dokumencie „!” — pojawi się lista snippetów (↑ ↓, Enter/Tab). Nazwa może mieć polskie litery.",
    snippetsNameLabel: "Nazwa (w dokumencie: !nazwa)",
    snippetsBodyLabel: "Treść bloku",
    snippetsSave: "Zapisz snippet",
    snippetsInsert: "Wstaw treść",
    snippetsInsertTrigger: "Wstaw !trigger",
    snippetsExpandModeLabel: "Rozwijanie w edycji",
    snippetsExpandManual: "Ręcznie (przycisk Rozwiń)",
    snippetsExpandAuto: "Auto po !nazwa + spacja lub interpunkcja",
    snippetsExpandModeSaved: "Zapisano tryb rozwijania snippetów",
    snippetsAutoExpanded: "Rozwinięto {name}",
    snippetsTriggerInserted: "Wstawiono trigger {name}",
    snippetsDynamicHint: "W treści: {date} {date:short} {date:iso} {date+14:short} {time} {day} {month} {year}, {cursor} — tu stanie kursor, {{pole}} — zapyta o wartość, !inny — snippet w snippecie. Nowa linia = łamanie wiersza.",
    snippetsScan: "Skanuj !triggery",
    snippetsExpand: "Rozwiń w dokumencie",
    snippetsUse: "Użyj",
    snippetsDelete: "Usuń",
    snippetsEmpty: "Brak zapisanych snippetów",
    snippetsNoTriggers: "Brak !triggerów w dokumencie",
    snippetsFound: "Znaleziono {count} triggerów ({total}×)",
    snippetsFoundMissing: "Znaleziono {count} triggerów ({total}×), brak definicji: {missing}",
    snippetsSaveInvalid: "Podaj nazwę (litera na początku) i treść snippetu",
    snippetsSaved: "Zapisano {name}",
    snippetsDeleteConfirm: "Usunąć snippet {name}?",
    snippetsExpandConfirm: "Rozwinąć {count} snippetów w dokumencie?",
    snippetsExpanded: "Rozwinięto {count} wystąpień",
    snippetsNothingToExpand: "Brak rozpoznanych !triggerów z definicją",
    snippetsInsertEmpty: "Brak treści snippetu",
    snippetsInsertNoCaret: "Ustaw kursor w akapicie w trybie edycji",
    snippetsInserted: "Wstawiono snippet",
    helpEditTitle: "Edycja w podglądzie",
    helpFrTitle: "Znajdź i zamień",
    helpFrText: "Skanuj trafienia przed zamianą; „Zamień bieżące” lub „Zamień wszystkie”.",
    helpGrammarTitle: "Korekta",
    helpGrammarText: "Offline — podwójne spacje, interpunkcja, cudzysłowy PL i inne reguły typografii.",
  },
  en: {
    locale: "en-US",
    title: "Documents Workbench",
    description: "Local viewing, editing, and analysis of Word documents",
    online: "Online",
    offline: "Offline",
    panelOpen: "Close panel",
    panelClosed: "Panel",
    noFile: "No file",
    loadingGeneric: "Loading…",
    loadingFile: "Loading document…",
    renderingDoc: "Rendering document…",
    savingFile: "Saving…",
    docLoaded: "Document loaded",
    sampleLoaded: "Sample document loaded",
    unsupportedType: "Supported formats: .docx (PDF coming soon)",
    pdfSoon: "PDF is not supported yet — open a .docx file.",
    docOldFormat: "This is the old .doc format — in Word use “Save as” → Word Document (.docx) and open that file.",
    libsMissingStatus: "Document libraries missing",
    libsMissingToast: "Could not load DOCX libraries",
    noFileToSave: "Load a document first",
    saveDone: "Document saved",
    saveFailed: "Could not save file",
    saveAsPrompt: "File name",
    saveInPlaceWarn: "Overwrite the original file?",
    saveDifferentFileWarn: "Selected file is “{name}”, not the current document. Overwrite anyway?",
    saveCancelled: "Save cancelled",
    savePickFileHint: "Select the .docx file you want to overwrite",
    savePermissionDenied: "No permission to save in place",
    editApplied: "Changes applied: {count}",
    editNothing: "No changes to apply",
    editErrNoFind: "Enter search text",
    editErrBadRegex: "Invalid regular expression",
    editErrNoAffix: "Enter a prefix or suffix",
    editToolNoChange: "No changes to apply",
    editOpLabel: "Operation",
    editOpReplace: "Find & replace",
    editOpCase: "Change case",
    editOpTrim: "Trim / spaces",
    editOpAffix: "Prefix / suffix",
    editCaseLabel: "Letter case",
    editCaseUpper: "UPPERCASE",
    editCaseLower: "lowercase",
    editCaseTitle: "Title Case",
    editTrimLabel: "Mode",
    editTrimEnds: "Trim ends",
    editTrimCollapse: "Collapse spaces",
    editTrimHard: "Replace hard spaces",
    editPrefixLabel: "Prefix (prepend)",
    editSuffixLabel: "Suffix (append)",
    inlineEditHint: "Enter — paragraph · Shift+Enter — line · Backspace — merge · Tab — list · Ctrl+Tab — heading · Ctrl+B/I/U — style · font size from list (inherits from paragraph)",
    searchNoMatches: "No matches",
    searchMatches: "{count} matches",
    readModeOn: "Read-only",
    readModeOff: "Edit mode",
    words: "Words",
    chars: "Characters",
    headings: "Headings",
    paragraphs: "Paragraphs",
    tables: "Tables",
    editToolsPanel: "Edit tools",
    editFindLabel: "Find",
    editReplaceLabel: "Replace with",
    editRegexLabel: "Regular expression",
    editScopeLabel: "Scope",
    editScopeAll: "Whole document",
    editScopeBody: "Main body",
    applyEdit: "Apply",
    searchPanel: "Search",
    frMatchCase: "Match case",
    frWholeWord: "Whole words only",
    frRegexHint: "In “Replace with”: $1, $2… = groups in parentheses, $& = whole match.",
    frScopeLabel: "Search in",
    frScopeAll: "All text",
    frScopeHeadings: "Section headings only",
    frOtherPartsLabel: "“Replace all” also in headers, footers and notes",
    frOtherFoundOn: "+{count} in headers, footers, notes (will be replaced too)",
    frOtherFoundOff: "+{count} in headers, footers, notes (tick the option to replace them too)",
    frReplaceAllOther: "Plus {count} in headers, footers and notes.",
    frListMore: "…and {count} more (use ↑ ↓)",
    grammarRescanned: "The text changed since the scan — suggestions refreshed, click again.",
    snippetsFieldsTitle: "Fill in the fields: {name}",
    snippetsFieldsHint: "Empty fields stay in the text as {{field}} — you can fill them later in the Placeholders panel.",
    snippetsFieldsInsert: "Insert",
    snippetsSuggestHint: "↑ ↓ choose · Enter/Tab insert · Esc close",
    snippetsStarter: "Add example snippets",
    snippetsStarterAdded: "Example snippets added: {count}",
    snippetsFilter: "Find a snippet…",
    snippetsInsertShort: "Insert",
    snippetsEdit: "Edit",
    snippetsUpdated: "Updated {name}",
    cancel: "Cancel",
    undoOpSnippet: "snippet",
    frPanel: "Find & replace",
    frPrev: "Previous",
    frNext: "Next",
    frScan: "Find",
    frReplaceOne: "Replace current",
    frReplaceAll: "Replace all",
    frMatchPos: "Match {pos} / {total}",
    frPreviewOnly: "Save preview: {hits} hits in {paras} paragraphs",
    frReplaceAllConfirm: "Replace {hits} occurrences in {paras} paragraphs?",
    frReplacedOne: "Replaced current match",
    searchQueryLabel: "Query",
    searchScopeLabel: "Scope",
    searchHighlight: "Highlight",
    structurePanel: "Structure",
    structureFilterLabel: "Show",
    structureFilterAll: "All",
    structureFilterHeadings: "Headings",
    structureFilterParagraphs: "Paragraphs",
    structureFilterTables: "Tables",
    structureTypeHeading: "Head.",
    structureTypeParagraph: "Para.",
    structureTypeTable: "Table",
    structureCopy: "Copy",
    structureEdit: "Edit",
    structureQuickEditLabel: "Quick paragraph edit",
    structureQuickApply: "Apply",
    structureQuickFocus: "Edit in preview",
    structureCopied: "Text copied",
    structureCopyFailed: "Could not copy",
    structureNoOutline: "No elements in document",
    structureNoFilterMatch: "No elements in this filter",
    structureEmptyPara: "(empty paragraph)",
    structureTablePreview: "Table {rows}×{cols}: {preview}",
    structureTableEmpty: "Table {rows}×{cols}",
    structureOutlineTruncated: "Showing {shown} of {total} items",
    structureSearchLabel: "Search structure",
    structureSearchPlaceholder: "phrase in heading or paragraph…",
    structurePageSizeLabel: "Per page",
    structurePageInfo: "{start}–{end} of {total} · page {page}/{pages}",
    structurePrevPage: "Previous",
    structureNextPage: "Next",
    structureSearchNoMatch: "No search matches",
    lockTracked: "This paragraph has tracked changes — accept or reject them in the Review panel to edit it.",
    lockNote: "This paragraph has a note reference — editing here would lose it. Edit it in Word.",
    lockObject: "This paragraph contains an image or object — editing here would lose it. Edit it in Word.",
    lockField: "This paragraph contains a field (e.g. page number, table of contents) — editing here would lose it.",
    lockLink: "This paragraph contains a link — editing here would lose it. Edit it in Word.",
    reviewPanel: "Review",
    reviewAuthorLabel: "Change author",
    reviewAcceptAllBtn: "Accept all",
    reviewRejectAllBtn: "Reject all",
    reviewAcceptAll: "Accept all",
    reviewRejectAll: "Reject all",
    reviewAcceptAuthor: "Accept: {author}",
    reviewRejectAuthor: "Reject: {author}",
    reviewAllAuthors: "All authors ({count})",
    reviewChangesHead: "Tracked changes",
    reviewCommentsHead: "Comments",
    reviewNotesHead: "Notes",
    reviewRemoveComments: "Delete all comments",
    reviewPreviewHint: "The preview shows the text as if changes were accepted (deletions are hidden). The list shows everything.",
    reviewSummary: "Changes: {changes} (authors: {authors}) · comments: {comments} · notes: {notes}",
    reviewNoChanges: "No tracked changes.",
    reviewNoComments: "No comments.",
    reviewNoNotes: "No footnotes or endnotes.",
    reviewShowMore: "Show the rest ({count})",
    reviewKindIns: "Inserted",
    reviewKindDel: "Deleted",
    reviewKindMoveFrom: "Moved from",
    reviewKindMoveTo: "Moved here",
    reviewKindFormat: "Formatting",
    reviewKindParaFormat: "Paragraph format",
    reviewKindOtherFormat: "Other layout change",
    reviewKindParaIns: "New paragraph",
    reviewKindParaDel: "Paragraphs joined",
    reviewKindRowIns: "Inserted row",
    reviewKindRowDel: "Deleted row",
    reviewInHeader: "in header",
    reviewInFooter: "in footer",
    reviewInFootnote: "in footnote",
    reviewInEndnote: "in endnote",
    reviewFootnote: "Footnote",
    reviewEndnote: "Endnote",
    reviewResolved: "resolved",
    reviewAcceptOne: "Accept change",
    reviewRejectOne: "Reject change",
    reviewDeleteComment: "Delete comment",
    reviewAcceptConfirm: "Accept changes ({count})?",
    reviewRejectConfirm: "Reject changes ({count})?",
    reviewRemoveCommentsConfirm: "Delete all comments ({count}) from the file?",
    reviewAccepted: "Accepted: {count}",
    reviewRejected: "Rejected: {count}",
    reviewCommentsRemoved: "Comments deleted: {count}",
    reviewOnOpen: "The document has tracked changes ({changes}) and comments ({comments}) — see the Review panel.",
    undoOpReview: "review",
    undoOpInsert: "insert",
    undoOpPaste: "paste",
    exportPanel: "Export",
    exportIntro: "Download the document text (with your edits) as plain text, Markdown or HTML. All local.",
    exportPrint: "Print / save as PDF",
    exportPrintHint: "In the print dialog choose “Save as PDF”. Page layout as in the preview.",
    exportEmpty: "The document has no text to export.",
    exportDone: "Saved {name}",
    exportPrintFail: "Could not open the print dialog.",
    statsPanel: "Statistics",
    statsWords: "Words",
    statsChars: "Characters",
    statsCharsNoSpaces: "Characters (no spaces)",
    statsSentences: "Sentences",
    statsParagraphs: "Paragraphs",
    statsTables: "Tables",
    statsReading: "Reading time",
    statsAvgSentence: "Words per sentence",
    statsUnderMinute: "< 1 min",
    statsMinutes: "{n} min",
    statsTopWords: "Most frequent words",
    statsNoRepeats: "No repeated words (4+ letters).",
    statsLongLimit: "Long sentence = more than (words)",
    statsLongHead: "Longest sentences",
    statsNoLong: "No sentences over the threshold.",
    statsWordsShort: "{n} words",
    statsRefresh: "Refresh",
    statsSelectionHint: "Select text in the document to see its statistics.",
    statsSelection: "Selection: {words} words · {chars} characters · reading {min}",
    metadataScrub: "Remove personal data",
    metadataScrubConfirm: "Clear author, last modified by, description and subject in the file?",
    metadataScrubbed: "Personal data removed from metadata.",
    metadataScrubNothing: "Metadata was already clean.",
    phExportValues: "Save values (JSON)",
    phImportValues: "Load values",
    phExported: "Saved values: {count}",
    phImported: "Loaded into fields: {filled} of {total}",
    snExportAll: "Export snippets",
    snImportAll: "Import snippets",
    snExported: "Exported snippets: {count}",
    snImported: "Import: {added} new, {updated} overwritten",
    importBadFile: "This is not a file from this app (JSON).",
    metadataPanel: "Metadata",
    metadataIntro: "File properties from docProps/core.xml — shown in Explorer / Word, not in document body.",
    metadataTitleLabel: "Title",
    metadataCreatorLabel: "Author",
    metadataKeywordsLabel: "Keywords",
    metadataReload: "Reload from file",
    metadataApply: "Apply",
    metadataHint: "Edit fields and click Apply to save into the file.",
    metadataSynced: "Matches file",
    metadataDirty: "Unsaved metadata changes",
    metadataApplied: "Metadata saved to file",
    filePanel: "File",
    viewPanel: "View",
    zoomLabel: "Zoom",
    zoomFit: "Fit to screen",
    zoomReset: "Page layout",
    zoomReflowHint: "Text reflows to screen width — the saved file stays unchanged.",
    dropText: "Drop a file",
    dropOr: "or click here",
    dropBtn: "Choose file",
    openFile: "Open file",
    emptyTitle: "Open a .docx document",
    emptySub: "Your file stays on this device — nothing is uploaded to a server.",
    loadSample: "Sample",
    save: "Save",
    saveAs: "Save as",
    // ── keyboard, focus mode (package E) ──
    skipToDoc: "Skip to the document",
    docRegionAria: "Document",
    focusModeAria: "Focus mode",
    focusModeExitAria: "Exit focus mode",
    focusModeMenu: "Focus mode",
    focusModeMenuExit: "Exit focus mode",
    focusModeOn: "Focus mode — press Esc or the same button to exit",
    focusModeOnTouch: "Focus mode — the same button brings the view back",
    fullscreenMenu: "Full screen",
    fullscreenMenuExit: "Exit full screen",
    fullscreenFailed: "The browser refused full screen — focus mode is on",
    helpKeysTitle: "Keyboard",
    helpKeysText: "Ctrl/⌘+F — search · Enter / Shift+Enter (or F3) — next / previous · Ctrl/⌘+S — save · Ctrl/⌘+Alt+E — Reading ⇄ Editing · Ctrl/⌘+Alt+F — focus mode · Ctrl/⌘+Alt+1 / 2 / 3 — panel / toolbar / document (F6 — in turn) · Esc — step back",
    // ── Undo / Redo (undo.js) ──
    undoGroupAria: "Undo and redo",
    helpUndoTitle: "Undo / Redo",
    helpUndoText: "Ctrl/⌘+Z — undo · Ctrl/⌘+Shift+Z or Ctrl+Y — redo · ↶ ↷ buttons in the toolbar. Undoes panel operations, formatting and typing (continuous typing = one step; a pause or a click starts a new one).",
    undoLabel: "Undo (Ctrl/⌘+Z)",
    redoLabel: "Redo (Ctrl/⌘+Shift+Z)",
    undoWhat: "Undo: {what} (Ctrl/⌘+Z)",
    redoWhat: "Redo: {what} (Ctrl/⌘+Shift+Z)",
    undoDone: "Undone: {what}",
    redoDone: "Redone: {what}",
    undoNothing: "Nothing to undo",
    redoNothing: "Nothing to redo",
    undoWorking: "Undoing…",
    redoWorking: "Redoing…",
    undoFailed: "Undo failed — details in the Log",
    undoOpTyping: "typing",
    undoOpFormat: "formatting",
    undoOpReplace: "text replace",
    undoOpCase: "letter case",
    undoOpTrim: "spaces",
    undoOpAffix: "prefix / suffix",
    undoOpParagraphs: "paragraph changes",
    undoOpMetadata: "metadata",
    undoOpPlaceholders: "field fill",
    undoOpSnippets: "snippet expansion",
    undoOpEdit: "change",
    // ── screen frame (package B, app-frame.js) ──
    heroSave: "Save changes to the file (Ctrl/⌘+S)",
    heroSaveDirty: "Save — {changes}",
    statusUnsaved: "unsaved: {changes}",
    changesOne: "1 change",
    changesFew: "{n} changes",
    changesMany: "{n} changes",
    appMenuAria: "App menu: language, theme, refresh",
    menuLang: "Language",
    menuTheme: "Theme",
    themeAria: "Switch light / dark theme",
    menuRefresh: "Refresh the app",
    menuOtherApps: "Other apps",
    heroGripAria: "Collapse or expand the header",
    finderPlaceholder: "Find a setting…",
    finderClear: "Clear",
    finderEmpty: "Nothing matches — try another word.",
    groupFile: "File",
    groupEdit: "Editing",
    groupTemplates: "Templates",
    groupNav: "Navigation",
    groupView: "View",
    groupHelp: "Help",
    frSearchInToolbar: "Type the search phrase in the field above the document (Enter, ↑ ↓). Here: replace and options.",
    showSectionChips: "Section shortcuts above the document",
    searchPlaceholder: "Search the document…",
    toolsAria: "Tools (panel)",
    modeAria: "Document mode",
    modeRead: "Reading",
    modeEdit: "Editing",
    zoomOut: "Zoom out",
    zoomFitShort: "Fit",
    zoomIn: "Zoom in",
    sectionStripHide: "Hide section shortcuts (turn them on in View)",
    sectionStripHidden: "Section shortcuts hidden — turn them on in the View panel",
    emptyOpen: "Choose a file",
    emptySample: "Try the sample document",
    emptyDropHint: "or drop a .docx file anywhere in the window",
    dropHere: "Drop the .docx file to open it",
    metaWords: "{n} words",
    metaParas: "{n} paragraphs",
    metaInPlace: "saves in place",
    metaSaveAs: "saves as a new file",
    updateApp: "Update",
    updateAvailable: "A new version is available — click “Update”",
    refreshingApp: "Refreshing…",
    cacheRefresh: "Refreshing the app…",
    closeDocWarn: "You have unsaved changes. Close the document?",
    closeDocAria: "Close document",
    docClosed: "Document closed",
    closeDoc: "Close document",
    introAria: "Mateusz intro",
    groupData: "Data",
    groupTools: "Analysis & editing",
    searchScopeAll: "Everything",
    searchScopeHeadings: "Headings",
    grammarPanel: "Proofing",
    grammarLangLabel: "Language",
    grammarNbspLabel: "Hard spaces (PL)",
    grammarScan: "Scan document",
    grammarApplyOne: "Apply",
    grammarApplyAll: "Apply all",
    grammarApplyRule: "Apply rule",
    grammarClear: "Clear",
    grammarNoHits: "No proofing suggestions",
    grammarFound: "Found: {hits} ({rules} rules)",
    grammarApplyAllConfirm: "Apply fixes in {count} paragraphs?",
    grammarAppliedOne: "Fix applied",
    grammarRuleDoubleSpace: "Double spaces",
    grammarRuleSpaceBeforePunct: "Space before punctuation",
    grammarRuleEllipsis: "Ellipsis",
    grammarRuleQuotesPl: "Polish quotation marks",
    grammarRuleCapAfterPeriod: "Capital after period",
    grammarRuleNbspPl: "Hard spaces after prepositions",
    placeholdersPanel: "Placeholders",
    placeholdersScan: "Scan fields",
    placeholdersFill: "Fill in",
    placeholdersClear: "Clear",
    placeholdersNoFields: "No {{…}} fields in document",
    placeholdersFound: "Found {count} fields ({total} occurrences)",
    placeholdersFillConfirm: "Fill {count} fields in the document?",
    placeholdersApplied: "Filled {count} occurrences",
    placeholdersFieldLabel: "Field",
    placeholdersEmptyValues: "Enter a value in at least one field",
    placeholdersHint: "Standalone {{name}} fields — type in the document or use Insert {{field}}, then Scan → Fill. No snippets required.",
    placeholdersInsertLabel: "Field name",
    placeholdersInsert: "Insert {{field}}",
    placeholdersInsertInvalid: "Enter a valid field name (letters, digits, _, -, .)",
    placeholdersInserted: "Inserted {token}",
    helpPanel: "Shortcuts & tips",
    helpPhTitle: "Placeholders {{field}}",
    helpPhIntro: "Templates with fill-in fields — no manual search through the document.",
    helpPhItem1: "Syntax: {{name}} — letters, digits, _, -, . (spaces inside braces are OK)",
    helpPhItem2: "Scan fields → enter values → Fill in → Save",
    helpPhItem3: "Empty form fields are skipped",
    helpPhItem4: "Same {{field}} in many places — one value replaces all",
    helpPhItem5: "Example: Agreement with {{first_name}} {{last_name}}, date {{date}}.",
    helpPhItem6: "Optional with snippets: expand !snippets first, then Fill {{placeholders}}",
    helpPhItem7: "Placeholders panel → Insert {{field}} puts a token at the caret",
    helpSnTitle: "Snippets !name",
    helpSnIntro: "Insertable text blocks — the ! prefix avoids accidental matches.",
    helpSnItem1: "Type !testsnippet + space — in Auto mode it expands immediately",
    helpSnItem2: "A snippet may contain {{placeholders}} — expand snippet, then fill fields",
    helpSnItem3: "Save your own snippet in the panel; use Insert !trigger or type manually",
    helpSnItem4: "Manual: Scan → Expand in document · Auto: after !name + space or punctuation",
    helpSnItem5: "Dynamic tokens in body: {date} {time} {datetime} {day} (Raycast-style)",
    fmtFontSizeLabel: "Font size",
    fmtFontSizeInherit: "Match paragraph",
    snippetsPanel: "Snippets",
    snippetsHint: "Type “!” in the document — a list of snippets appears (↑ ↓, Enter/Tab). Names may use any letters.",
    snippetsNameLabel: "Name (in document: !name)",
    snippetsBodyLabel: "Block text",
    snippetsSave: "Save snippet",
    snippetsInsert: "Insert body",
    snippetsInsertTrigger: "Insert !trigger",
    snippetsExpandModeLabel: "Expand while editing",
    snippetsExpandManual: "Manual (Expand button)",
    snippetsExpandAuto: "Auto after !name + space or punctuation",
    snippetsExpandModeSaved: "Snippet expand mode saved",
    snippetsAutoExpanded: "Expanded {name}",
    snippetsTriggerInserted: "Inserted trigger {name}",
    snippetsDynamicHint: "In the body: {date} {date:short} {date:iso} {date+14:short} {time} {day} {month} {year}, {cursor} — caret goes here, {{field}} — asks for a value, !other — snippet inside a snippet. New line = line break.",
    snippetsScan: "Scan !triggers",
    snippetsExpand: "Expand in document",
    snippetsUse: "Use",
    snippetsDelete: "Delete",
    snippetsEmpty: "No saved snippets",
    snippetsNoTriggers: "No !triggers in document",
    snippetsFound: "Found {count} triggers ({total}×)",
    snippetsFoundMissing: "Found {count} triggers ({total}×), missing definitions: {missing}",
    snippetsSaveInvalid: "Enter a valid name (starts with a letter) and body text",
    snippetsSaved: "Saved {name}",
    snippetsDeleteConfirm: "Delete snippet {name}?",
    snippetsExpandConfirm: "Expand {count} snippets in the document?",
    snippetsExpanded: "Expanded {count} occurrences",
    snippetsNothingToExpand: "No recognized !triggers with a saved definition",
    snippetsInsertEmpty: "Snippet body is empty",
    snippetsInsertNoCaret: "Place the caret in a paragraph in edit mode",
    snippetsInserted: "Snippet inserted",
    helpEditTitle: "Inline editing",
    helpFrTitle: "Find & replace",
    helpFrText: "Scan matches before replacing; Replace current or Replace all.",
    helpGrammarTitle: "Proofing",
    helpGrammarText: "Offline — double spaces, punctuation, Polish quotes, and other typography rules.",
  },
};

function t(key, vars) {
  const copy = I18N[currentLang][key] ?? I18N.pl[key] ?? key;
  if (!vars) return copy;
  return copy.replace(/\{(\w+)\}/g, (_, k) => (vars[k] != null ? String(vars[k]) : ""));
}

function applyLanguage() {
  const copy = I18N[currentLang];
  BASE_TITLE = copy.title;
  document.documentElement.lang = currentLang;
  const desc = document.getElementById("pageDescription");
  if (desc) desc.setAttribute("content", copy.description);
  if (!hasUnsavedChanges) document.title = copy.title;
  document.querySelectorAll("[data-i18n]").forEach((el) => {
    const key = el.dataset.i18n;
    if (copy[key]) el.textContent = copy[key];
  });
  document.querySelectorAll("[data-i18n-aria]").forEach((el) => {
    const key = el.dataset.i18nAria;
    if (copy[key]) el.setAttribute("aria-label", copy[key]);
  });
  document.querySelectorAll("[data-i18n-placeholder]").forEach((el) => {
    const key = el.dataset.i18nPlaceholder;
    if (copy[key]) el.placeholder = copy[key];
  });
  const introVid = document.getElementById("introVideo");
  if (introVid && copy.introAria) introVid.setAttribute("aria-label", copy.introAria);
  document.querySelectorAll(".lang-button").forEach((btn) => {
    const on = btn.dataset.lang === currentLang;
    btn.classList.toggle("is-active", on);
    btn.setAttribute("aria-pressed", on ? "true" : "false");
  });
  if (typeof syncLangSwitchPill === "function") syncLangSwitchPill();
  if (documentStructure && typeof renderStructurePanel === "function") renderStructurePanel(documentStructure);
  if (typeof appFrame !== "undefined") appFrame.onLanguageChange();
  if (typeof dwbUndo !== "undefined") dwbUndo.sync();
  if (typeof dwbView !== "undefined") dwbView.syncMenu();
}

function setLanguage(lang) {
  currentLang = lang === "en" ? "en" : "pl";
  localStorage.setItem(LANG_KEY, currentLang);
  applyLanguage();
}
